include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - ios/Pods/**
    - ios/.symlinks/**
    - ios/SourcePackages/**
    - ios/Flutter/ephemeral/**
    - ios/Flutter/Generated.xcconfig
    - ios/Flutter/flutter_export_environment.sh
    - ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/**
    - ios/Runner.xcworkspace/xcshareddata/swiftpm/**
    - third_party/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
  errors:
    close_sinks: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    prefer_single_quotes: ignore
    unnecessary_lambdas: ignore
    unnecessary_underscores: ignore

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    cancel_subscriptions: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
