import type { Locale } from "@/lib/i18n";

const ru = {
  title: "Главная каталога",
  intro: "Категории, обложки и подборки для экрана «Обзор».",
  draft: "Черновик",
  published: "Опубликовано",
  automatic: "Автоматическая витрина",
  create: "Создать черновик",
  save: "Сохранить черновик",
  publish: "Опубликовать",
  reload: "Загрузить актуальную версию",
  discard: "Отменить черновик",
  layout: "Компоновка",
  settings: "Тексты и поведение",
  history: "История",
  sections: "Секции страницы",
  add: "Добавить категорию",
  selectCategory: "Выберите категорию",
  empty: "Добавьте первую категорию",
  enabled: "Секция включена",
  carousel: "В верхней карусели",
  rail: "В горизонтальной ленте",
  category: "Категория",
  contentLocale: "Язык контента",
  pageTitle: "Заголовок страницы",
  pageSubtitle: "Подзаголовок страницы",
  sectionTitle: "Название секции",
  sectionSubtitle: "Подзаголовок секции",
  translationHint:
    "Пустой перевод использует английский текст. Язык контента не меняет язык admin.",
  search: "Показывать поиск",
  showCarousel: "Показывать верхнюю карусель",
  autoplay: "Автоматическая прокрутка",
  interval: "Интервал, секунды",
  mode: "Наполнение",
  Latest: "Новые автоматически",
  Manual: "Только вручную",
  Hybrid: "Закреплённые + новые",
  latestHint: "Новые публичные шаблоны категории. Обложку можно закрепить отдельно.",
  hybridHint: "Закреплённые карточки идут первыми, остальные места заполняются новыми шаблонами.",
  manualHint: "Показываются выбранные карточки. Обложка занимает первое место.",
  limit: "Карточек в секции",
  cover: "Обложка карусели",
  automaticCover: "Первая доступная карточка",
  chooseCover: "Сделать обложкой",
  pin: "Закрепить",
  unpin: "Убрать",
  pinned: "Порядок карточек",
  templateSearch: "Поиск шаблона в категории",
  noTemplates: "Нет подходящих шаблонов",
  available: "Доступные шаблоны",
  remove: "Удалить секцию",
  up: "Выше",
  down: "Ниже",
  previous: "Назад",
  next: "Далее",
  preview: "Предпросмотр",
  previewHint: "Результат сервера для сохранённой версии. Стиль mobile может отличаться.",
  previewStale: "Есть изменения: сохраните черновик, чтобы обновить preview.",
  previewLoading: "Загружаем предпросмотр…",
  previewEmpty: "В этой версии пока нет доступных карточек.",
  saved: "Черновик сохранён",
  publishedNotice: "Витрина опубликована",
  restored: "Версия восстановлена в новый черновик",
  discarded: "Черновик отменён",
  loading: "Загружаем витрину…",
  failed: "Не удалось выполнить действие. Попробуйте ещё раз.",
  conflict:
    "Версия на сервере изменилась. Ваши правки сохранены в форме. Загрузите актуальную версию, чтобы продолжить.",
  dirty: "Не сохранено",
  clean: "Сохранено",
  readonly: "Доступ только для просмотра",
  validation: "Проверка публикации",
  valid: "Конфигурация прошла проверку",
  publishTitle: "Опубликовать витрину?",
  publishDescription:
    "Эта версия станет доступна пользователям после обновления каталога в приложении.",
  reason: "Что изменилось",
  reasonPlaceholder: "Например: новая подборка Funny и порядок категорий",
  cancel: "Отмена",
  restore: "Восстановить в черновик",
  restoreTitle: "Восстановить эту версию?",
  restoreDescription: "Создадим новый черновик. После проверки его можно опубликовать.",
  discardTitle: "Отменить черновик?",
  discardDescription:
    "Рабочая версия останется в истории. Опубликованная витрина продолжит работать.",
  reloadTitle: "Загрузить версию с сервера?",
  reloadDescription: "Несохранённые изменения этой формы будут потеряны.",
  leave: "Есть несохранённые изменения витрины. Покинуть страницу?",
  added: "Добавлено секций",
  removed: "Удалено секций",
  changed: "Изменено секций",
  reordered: "Изменён порядок",
  pageChanged: "Изменены настройки страницы",
  yes: "Да",
  no: "Нет",
  revision: "Версия",
  date: "Обновлено",
  status: "Состояние",
  noHistory: "История появится после создания первого черновика.",
  Draft: "Черновик",
  Published: "Публиковалась",
  Discarded: "Отменена",
  more: "Ещё",
  searchPlaceholder: "Поиск шаблонов",
  sectionCount: "секций",
  retry: "Повторить",
};
type DiscoveryText = { [K in keyof typeof ru]: string };
const en: DiscoveryText = {
  title: "Discovery page",
  intro: "Categories, covers and collections for the Discover screen.",
  draft: "Draft",
  published: "Published",
  automatic: "Automatic discovery",
  create: "Create draft",
  save: "Save draft",
  publish: "Publish",
  reload: "Load current version",
  discard: "Discard draft",
  layout: "Layout",
  settings: "Copy & behavior",
  history: "History",
  sections: "Page sections",
  add: "Add category",
  selectCategory: "Select a category",
  empty: "Add your first category",
  enabled: "Section enabled",
  carousel: "In the top carousel",
  rail: "In a horizontal rail",
  category: "Category",
  contentLocale: "Content language",
  pageTitle: "Page title",
  pageSubtitle: "Page subtitle",
  sectionTitle: "Section title",
  sectionSubtitle: "Section subtitle",
  translationHint:
    "Empty translations fall back to English. Content language is independent of admin language.",
  search: "Show search",
  showCarousel: "Show top carousel",
  autoplay: "Automatic advance",
  interval: "Interval, seconds",
  mode: "Selection",
  Latest: "Latest automatically",
  Manual: "Manual only",
  Hybrid: "Pinned + latest",
  latestHint: "Latest public templates in this category. A cover can be pinned separately.",
  hybridHint: "Pinned cards appear first. Latest templates fill the remaining slots.",
  manualHint: "Only selected cards appear. The cover occupies the first slot.",
  limit: "Cards per section",
  cover: "Carousel cover",
  automaticCover: "First available card",
  chooseCover: "Use as cover",
  pin: "Pin",
  unpin: "Remove",
  pinned: "Card order",
  templateSearch: "Search this category",
  noTemplates: "No eligible templates",
  available: "Available templates",
  remove: "Remove section",
  up: "Move up",
  down: "Move down",
  previous: "Previous",
  next: "Next",
  preview: "Preview",
  previewHint: "Server result for the saved revision. Mobile styling may differ.",
  previewStale: "Save your changes to update the preview.",
  previewLoading: "Loading preview…",
  previewEmpty: "No available cards in this revision yet.",
  saved: "Draft saved",
  publishedNotice: "Discovery page published",
  restored: "Revision restored into a new draft",
  discarded: "Draft discarded",
  loading: "Loading discovery…",
  failed: "The action failed. Please try again.",
  conflict:
    "The server version changed. Your edits are still in the form. Load the current version to continue.",
  dirty: "Unsaved changes",
  clean: "Saved",
  readonly: "Read-only access",
  validation: "Publication validation",
  valid: "Configuration passed validation",
  publishTitle: "Publish discovery?",
  publishDescription: "Users will receive this revision when their app refreshes the catalog.",
  reason: "What changed",
  reasonPlaceholder: "For example: new Funny collection and category order",
  cancel: "Cancel",
  restore: "Restore as draft",
  restoreTitle: "Restore this revision?",
  restoreDescription: "A new draft will be created. Review it before publishing.",
  discardTitle: "Discard draft?",
  discardDescription: "The draft remains in history. Published discovery stays live.",
  reloadTitle: "Load the server version?",
  reloadDescription: "Unsaved form changes will be lost.",
  leave: "You have unsaved discovery changes. Leave this page?",
  added: "Sections added",
  removed: "Sections removed",
  changed: "Sections changed",
  reordered: "Order changed",
  pageChanged: "Page settings changed",
  yes: "Yes",
  no: "No",
  revision: "Revision",
  date: "Updated",
  status: "State",
  noHistory: "History will appear after the first draft is created.",
  Draft: "Draft",
  Published: "Published before",
  Discarded: "Discarded",
  more: "More",
  searchPlaceholder: "Search templates",
  sectionCount: "sections",
  retry: "Retry",
};
export const getDiscoveryText = (locale: Locale): DiscoveryText => (locale === "ru" ? ru : en);
export type { DiscoveryText };
