FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS builder
WORKDIR /src
COPY ["src/", "src/"]
RUN dotnet restore "src/Host/PetMagic.Host.Api/PetMagic.Host.Api.csproj"
RUN dotnet publish "src/Host/PetMagic.Host.Api/PetMagic.Host.Api.csproj" -c Release --no-restore -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/publish .
RUN mkdir -p /app/wwwroot/support-attachments /app/wwwroot/user-avatars /app/wwwroot/templates-media
EXPOSE 5000
ENTRYPOINT ["dotnet", "PetMagic.Host.Api.dll"]
