# syntax=docker/dockerfile:1.7
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder
WORKDIR /src
COPY ["src/", "src/"]
RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet restore "src/Host/PetMagic.Host.Api/PetMagic.Host.Api.csproj" \
    -r linux-x64 \
    -p:PublishReadyToRun=true \
    --verbosity normal
RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet publish "src/Host/PetMagic.Host.Api/PetMagic.Host.Api.csproj" \
    -c Release \
    --no-restore \
    -r linux-x64 \
    --self-contained false \
    -o /app/publish \
    -p:PublishReadyToRun=true

FROM mcr.microsoft.com/dotnet/aspnet:10.0
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/publish .
RUN mkdir -p /app/wwwroot/support-attachments /app/wwwroot/user-avatars /app/wwwroot/templates-media
EXPOSE 5000
ENTRYPOINT ["dotnet", "PetMagic.Host.Api.dll"]
