namespace PetMagic.Modules.Templates.Domain;

public static class TemplateAnalyticsEventTypes
{
    public const string View = "view";
    public const string VideoView = "video_view";
    public const string Complaint = "complaint";
    public const string Feedback = "feedback";
    public const string FeedbackPromptViewed = "feedback_prompt_viewed";
    public const string FeedbackRatingSelected = "feedback_rating_selected";
    public const string FeedbackSubmitted = "feedback_submitted";
    public const string FeedbackSubmitFailed = "feedback_submit_failed";
    public const string FeedbackReportClicked = "feedback_report_clicked";
    public const string AdminStatusChanged = "feedback_admin_status_changed";
    public const string AdminRefundIssued = "feedback_admin_refund_issued";
    public const string ResultViewed = "result_viewed";
    public const string RemoveClicked = "remove_clicked";
    public const string PaywallViewed = "paywall_viewed";
    public const string RemovedCredit = "removed_credit";
    public const string RemovedPremium = "removed_premium";
    public const string DownloadWatermarked = "download_watermarked";
    public const string DownloadClean = "download_clean";
    public const string ShareWatermarked = "share_watermarked";
    public const string ShareClean = "share_clean";
    public const string UseAsInputClicked = "use_as_input_clicked";
    public const string TemplateOfTheDayViewed = "viewed";
    public const string TemplateOfTheDayClicked = "clicked";
    public const string TemplateOfTheDayOpened = "opened";
    public const string TemplateSelected = "template_selected";
    public const string GenerationStarted = "generation_started";
    public const string GenerationCompleted = "generation_completed";
    public const string GenerationFailed = "generation_failed";
    public const string CreateVideoClicked = "create_video_clicked";
    public const string CompareClicked = "compare_clicked";
    public const string CompareViewed = "compare_viewed";
    public const string CompareSliderMoved = "compare_slider_moved";
    public const string CompareShareClicked = "compare_share_clicked";
    public const string CompareClosed = "compare_closed";
    public const string GenerateSimilarClicked = "generate_similar_clicked";
    public const string GenerateSimilarConfirmed = "generate_similar_confirmed";
    public const string GenerateSimilarStarted = "generate_similar_started";
    public const string GenerateSimilarCompleted = "generate_similar_completed";
    public const string GenerateSimilarFailed = "generate_similar_failed";
    public const string GenerateSimilarInsufficientCredits = "generate_similar_insufficient_credits";
    public const string PetCreated = "pet_created";
    public const string PetUpdated = "pet_updated";
    public const string PetDeleted = "pet_deleted";
    public const string PhotoUploaded = "photo_uploaded";
    public const string PhotoSetAvatar = "photo_set_avatar";
    public const string PhotoFavorited = "photo_favorited";
    public const string GenerateWithPetClicked = "generate_with_pet_clicked";
    public const string GenerationStartedFromPet = "generation_started_from_pet";
}
