import { type Locale } from "@/lib/i18n";

const templatesDailyFeaturedPageText = {
  ru: {
    intlLocale: "ru-RU",
    eyebrow: "Шаблоны",
    title: "Шаблон дня",
    description:
      "Планируйте витрину шаблона дня: ручные назначения, предпросмотр и автоматический выбор.",
    heroBadge: "Витрина дня",
    refresh: "Обновить",
    retry: "Повторить",
    current: "Текущий выбор",
    schedule: "Расписание",
    assignments: "назначений",
    form: "Назначение",
    formDescription:
      "Выберите активный шаблон, период показа и текст для карточки в мобильной витрине.",
    formAdminOnly: "Для изменений нужна роль администратора.",
    templateSearch: "Поиск шаблона",
    templateSearchPlaceholder: "Название, категория или тег",
    templateTypeFilter: "Тип шаблона",
    templateAccessFilter: "Тариф",
    allTemplateTypes: "Все типы",
    allAccessLevels: "Все тарифы",
    activeTemplatesOnly: "Статус: активные",
    template: "Шаблон",
    selectTemplate: "Выберите шаблон",
    startDate: "Дата начала",
    endDate: "Дата окончания",
    priority: "Приоритет",
    active: "Активно",
    inactive: "Отключено",
    titleOverride: "Заголовок для витрины",
    subtitleOverride: "Описание для витрины",
    badgeOverride: "Текст бейджа",
    save: "Сохранить",
    create: "Создать",
    reset: "Очистить",
    edit: "Изменить",
    delete: "Удалить",
    cancel: "Отмена",
    deleteConfirmTitle: "Удалить назначение?",
    deleteConfirmDescription: (templateTitle: string) =>
      `Удалить назначение "${templateTitle}" из расписания? Текущий мобильный показ обновится после сохранения.`,
    editAssignmentLabel: (templateTitle: string) => `Изменить назначение ${templateTitle}`,
    deleteAssignmentLabel: (templateTitle: string) => `Удалить назначение ${templateTitle}`,
    preview: "Предпросмотр",
    previewEmptyTitle: "Выберите шаблон",
    previewEmptySubtitle: "Здесь появится карточка витрины до сохранения назначения.",
    noCurrent: "На сегодня назначение не найдено.",
    noSchedule: "Расписание пока пустое.",
    dateOccupiedWarning:
      "На выбранные даты уже есть активное ручное назначение. Версия v1 поддерживает одно ручное назначение на дату.",
    invalidDateRangeWarning: "Дата окончания не может быть раньше даты начала.",
    autoPickDateRequired: "Выберите дату для ручного автовыбора.",
    noTemplates: "Активные шаблоны по этому запросу не найдены.",
    loading: "Загружаем витрину дня.",
    loadingTemplates: "Ищем активные шаблоны.",
    loadError: "Не удалось загрузить витрину дня.",
    saveError: "Не удалось сохранить назначение.",
    autoPick: "Автовыбор",
    autoPickDescription:
      "Управляет резервным выбором и ежедневным заданием. Ручной запуск ниже создаёт подбор на выбранную дату.",
    autoMode: "Авторежим",
    autoModeEnabled: "Включен",
    autoModeDisabled: "Отключен",
    autoModeStatus: "Статус авторежима",
    autoModeSave: "Сохранить настройки",
    autoPickRun: "Запустить автовыбор",
    allowedTypes: "Типы",
    allowedBoth: "Изображения и видео",
    excludeRecent: "Исключить последние дни",
    manual: "Ручной",
    auto: "Авто",
    premium: "Premium",
    free: "Бесплатно",
    image: "Изображение",
    video: "Видео",
    date: "Период",
    mode: "Режим",
    status: "Статус",
    actions: "Действия",
    titleLabel: "Заголовок",
    subtitleLabel: "Описание",
    badgeLabel: "Бейдж",
  },
  en: {
    intlLocale: "en-US",
    eyebrow: "Templates",
    title: "Daily Featured",
    description:
      "Schedule Template of the Day with manual assignments, preview, and automatic fallback picks.",
    heroBadge: "Template of the Day",
    refresh: "Refresh",
    retry: "Retry",
    current: "Current pick",
    schedule: "Schedule",
    assignments: "assignments",
    form: "Assignment",
    formDescription: "Choose an active template, display window, and mobile storefront copy.",
    formAdminOnly: "Admin role required to make changes.",
    templateSearch: "Template search",
    templateSearchPlaceholder: "Title, category, or tag",
    templateTypeFilter: "Template type",
    templateAccessFilter: "Access",
    allTemplateTypes: "All types",
    allAccessLevels: "All access levels",
    activeTemplatesOnly: "Status: Active",
    template: "Template",
    selectTemplate: "Select template",
    startDate: "Start date",
    endDate: "End date",
    priority: "Priority",
    active: "Active",
    inactive: "Disabled",
    titleOverride: "Storefront title",
    subtitleOverride: "Storefront subtitle",
    badgeOverride: "Badge text",
    save: "Save",
    create: "Create",
    reset: "Reset",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    deleteConfirmTitle: "Delete assignment?",
    deleteConfirmDescription: (templateTitle: string) =>
      `Delete "${templateTitle}" from the schedule? The current mobile storefront pick will update after the change is saved.`,
    editAssignmentLabel: (templateTitle: string) => `Edit ${templateTitle} assignment`,
    deleteAssignmentLabel: (templateTitle: string) => `Delete ${templateTitle} assignment`,
    preview: "Preview",
    previewEmptyTitle: "Select a template",
    previewEmptySubtitle: "The storefront card preview appears here before saving.",
    noCurrent: "No assignment is active today.",
    noSchedule: "No scheduled assignments yet.",
    dateOccupiedWarning:
      "The selected dates already have an active manual assignment. v1 supports one manual assignment per date.",
    invalidDateRangeWarning: "End date cannot be earlier than start date.",
    autoPickDateRequired: "Select a date before running auto-pick.",
    noTemplates: "No active templates match this search.",
    loading: "Loading daily featured.",
    loadingTemplates: "Searching active templates.",
    loadError: "Failed to load daily featured.",
    saveError: "Failed to save assignment.",
    autoPick: "Auto-pick",
    autoPickDescription:
      "Controls fallback picks and the daily job. The run action below creates a pick for a selected date.",
    autoMode: "Auto mode",
    autoModeEnabled: "Enabled",
    autoModeDisabled: "Disabled",
    autoModeStatus: "Auto mode status",
    autoModeSave: "Save settings",
    autoPickRun: "Run auto-pick",
    allowedTypes: "Allowed types",
    allowedBoth: "Images and videos",
    excludeRecent: "Exclude recent days",
    manual: "Manual",
    auto: "Auto",
    premium: "Premium",
    free: "Free",
    image: "Image",
    video: "Video",
    date: "Date",
    mode: "Mode",
    status: "Status",
    actions: "Actions",
    titleLabel: "Title",
    subtitleLabel: "Subtitle",
    badgeLabel: "Badge",
  },
} as const;

export type TemplatesDailyFeaturedPageText = (typeof templatesDailyFeaturedPageText)["en"];

export function getTemplatesDailyFeaturedPageText(locale: Locale): TemplatesDailyFeaturedPageText {
  return templatesDailyFeaturedPageText[locale] as TemplatesDailyFeaturedPageText;
}

export function getTemplatesDailyFeaturedPageIntlLocale(locale: Locale): string {
  return templatesDailyFeaturedPageText[locale].intlLocale;
}
