import { type Locale } from "@/lib/i18n";

const templatesCategoriesViewText = {
  ru: {
    actionsAdminOnly: "Управление категориями доступно только Admin.",
    notificationTitle: "Категории шаблонов",
    createSuccess: "Категория создана.",
    createError: "Не удалось создать категорию.",
    updateSuccess: "Категория обновлена.",
    updateError: "Не удалось обновить категорию.",
    archiveSuccess: "Категория отправлена в архив.",
    restoreSuccess: "Категория возвращена из архива.",
    archiveError: "Не удалось изменить состояние категории.",
    deleteSuccess: "Категория удалена.",
    deleteError: "Не удалось удалить категорию.",
    heroEyebrow: "Структура каталога",
    heroTitle: "Категории шаблонов",
    heroDescription:
      "Управляйте списком категорий, архивом и переименованием. Переименование категории автоматически обновляет связанные шаблоны.",
    crudEnabled: "CRUD подключен",
    readOnly: "Только просмотр",
    activeTab: "Активные",
    archiveTab: "Архив",
    categoriesMeta: "Категорий",
    templatesMeta: "Шаблонов",
    retry: "Повторить",
    totalCategories: "Всего категорий",
    totalCategoriesHint: "Категории в реестре",
    activeCategories: "Активные категории",
    activeCategoriesHint: "Доступны для новых шаблонов",
    archiveLabel: "Архив",
    archivedCategoriesHint: "Скрыты для новых шаблонов",
    totalTemplates: "Всего шаблонов",
    totalTemplatesHint: "Видео и изображения вместе",
    newCategoryTitle: "Новая категория",
    newCategoryDescription:
      "Сначала создайте категорию здесь, затем она появится в редакторах шаблонов.",
    categoryPlaceholder: "Например, Portrait Pets",
    addCategory: "Добавить категорию",
    categoriesTitle: "Категории",
    archivedDescription:
      "Архивные категории остаются в статистике и в связанных шаблонах, но не предлагаются для новых шаблонов.",
    activeDescription:
      "Переименование категории синхронно обновляет поле category у связанных шаблонов.",
    empty: "Категории не найдены.",
    state: "Состояние",
    total: "Всего",
    archivedStatus: "Архив",
    activeStatus: "Активна",
    save: "Сохранить",
    cancel: "Отмена",
    restore: "Вернуть",
    restoreDialogTitle: "Вернуть категорию?",
    archiveDialogTitle: "Архивировать категорию?",
    deleteDialogTitle: "Удалить категорию?",
    restoreDialogDescription: (name: string) => `Вернуть категорию "${name}" в активный список?`,
    archiveDialogDescription: (name: string) =>
      `Архивировать категорию "${name}"? Она останется в связанных шаблонах, но не будет доступна для новых шаблонов.`,
    deleteDialogDescription: (name: string) =>
      `Удалить категорию "${name}"? Категория удаляется только если в ней нет шаблонов.`,
    videoCategoryLabel: (name: string) => `Открыть видео-шаблоны категории ${name}`,
    imageCategoryLabel: (name: string) => `Открыть image-шаблоны категории ${name}`,
    editCategoryLabel: (name: string) => `Переименовать категорию ${name}`,
    archiveCategoryLabel: (name: string) => `Архивировать категорию ${name}`,
    restoreCategoryLabel: (name: string) => `Вернуть категорию ${name}`,
    deleteCategoryLabel: (name: string) => `Удалить категорию ${name}`,
  },
  en: {
    actionsAdminOnly: "Template category management is available to Admin only.",
    notificationTitle: "Template categories",
    createSuccess: "Category created.",
    createError: "Could not create category.",
    updateSuccess: "Category updated.",
    updateError: "Could not update category.",
    archiveSuccess: "Category archived.",
    restoreSuccess: "Category restored from archive.",
    archiveError: "Could not change category state.",
    deleteSuccess: "Category deleted.",
    deleteError: "Could not delete category.",
    heroEyebrow: "Template taxonomy",
    heroTitle: "Template Categories",
    heroDescription:
      "Manage the category registry, archive state, and rename flows. Renaming a category updates linked templates automatically.",
    crudEnabled: "CRUD enabled",
    readOnly: "Read-only",
    activeTab: "Active",
    archiveTab: "Archive",
    categoriesMeta: "Categories",
    templatesMeta: "Templates",
    retry: "Retry",
    totalCategories: "Total categories",
    totalCategoriesHint: "Categories in the registry",
    activeCategories: "Active categories",
    activeCategoriesHint: "Available for new templates",
    archiveLabel: "Archive",
    archivedCategoriesHint: "Hidden from new template assignment",
    totalTemplates: "Total templates",
    totalTemplatesHint: "Video and image combined",
    newCategoryTitle: "New category",
    newCategoryDescription:
      "Create categories here first so they become available in template editors.",
    categoryPlaceholder: "For example, Portrait Pets",
    addCategory: "Add category",
    categoriesTitle: "Categories",
    archivedDescription:
      "Archived categories stay in stats and linked templates, but are not suggested for new templates.",
    activeDescription:
      "Renaming a category synchronously updates the category field on linked templates.",
    empty: "No categories found.",
    state: "State",
    total: "Total",
    archivedStatus: "Archived",
    activeStatus: "Active",
    save: "Save",
    cancel: "Cancel",
    restore: "Restore",
    restoreDialogTitle: "Restore category?",
    archiveDialogTitle: "Archive category?",
    deleteDialogTitle: "Delete category?",
    restoreDialogDescription: (name: string) => `Restore category "${name}" to the active list?`,
    archiveDialogDescription: (name: string) =>
      `Archive category "${name}"? It will stay on linked templates but won't be available for new templates.`,
    deleteDialogDescription: (name: string) =>
      `Delete category "${name}"? It can only be removed when no templates reference it.`,
    videoCategoryLabel: (name: string) => `Open video templates in ${name}`,
    imageCategoryLabel: (name: string) => `Open image templates in ${name}`,
    editCategoryLabel: (name: string) => `Rename category ${name}`,
    archiveCategoryLabel: (name: string) => `Archive category ${name}`,
    restoreCategoryLabel: (name: string) => `Restore category ${name}`,
    deleteCategoryLabel: (name: string) => `Delete category ${name}`,
  },
} as const;

export type TemplatesCategoriesViewText = (typeof templatesCategoriesViewText)["en"];

export function getTemplatesCategoriesViewText(locale: Locale): TemplatesCategoriesViewText {
  return templatesCategoriesViewText[locale] as TemplatesCategoriesViewText;
}
