import { type Locale } from "@/lib/i18n";

const templateTestPageText = {
  ru: {
    intlLocale: "ru-RU",
    fileFallback: "Файл",
    noPhotoSelected: "Фото не выбрано",
    chooseImageFile: "Выберите image/* файл",
    petMagicBilling: "Стоимость PetMagic",
    falMotionCost: "Стоимость Fal",
    falImageCost: "Стоимость Fal",
    falInference: "Fal inference",
    falImageInference: "Fal image inference",
    waitingToStart: "Ожидает запуска",
    templateFallback: "Шаблон",
    imageModelFallback: "Image model",
    stageOne: "Этап 01",
    stageTwo: "Этап 02",
    preprocessing: "Препроцессинг",
    normalizedPhoto: "Нормализованное фото",
    preprocessingPending: "Карточка заполнится сразу после завершения препроцессинга.",
    preprocessingEmpty: "Загрузите фото питомца, чтобы подготовить кадр для генерации движения.",
    finalVideo: "Финальное видео",
    finalImage: "Финальное изображение",
    result: "Result",
    readyVideo: "Готовый ролик",
    readyImage: "Готовое изображение",
    videoProcessing:
      "Видео собирается. После завершения здесь появятся просмотр и скачивание.",
    imageProcessing:
      "Изображение генерируется. После завершения здесь появятся просмотр и скачивание.",
    videoReadyEmpty:
      "После генерации здесь всегда будут доступны просмотр и скачивание финального видео.",
    imageReadyEmpty:
      "После генерации здесь будут доступны просмотр и скачивание итогового изображения.",
    open: "Открыть",
    download: "Скачать",
    loadingWorkspace: "Загрузка тестового стенда...",
    templateNotFound: "Шаблон не найден.",
    retry: "Повторить",
    videoTemplates: "Видео шаблоны",
    imageTemplates: "Шаблоны изображений",
    templateTest: "Тест шаблона",
    backToCatalog: "К каталогу",
    openEditor: "Открыть редактор",
    generationResult: "Результат генерации",
    launching: "Запуск...",
    running: "В работе...",
    generateTest: "Сгенерировать тест",
    generationTime: "Время генерации",
    lastUpdate: "Последнее обновление",
    generationEvents: "События генерации",
    done: "Готово",
    runningShort: "В работе",
    timelineEmpty: "После запуска здесь появятся этапы тестовой генерации.",
    runSummary: "Сводка запуска",
    testHistory: "История тестов",
    attempt: "Попытка",
    started: "Старт",
    completed: "Завершён",
    status: "Статус",
    created: "Создан",
    imageGenerationCompleted: "Генерация изображения завершена",
    falImageRequest: "Fal image request",
    falImageInferenceDetail: "Fal image inference",
    mediaImport: "Импорт медиа",
    failureCode: "Код ошибки",
    preprocessingCompleted: "Препроцессинг завершён",
    falPreprocessRequest: "Fal preprocess request",
    falPreprocessInference: "Fal preprocess inference",
    motionCompleted: "Motion завершён",
    falMotionRequest: "Fal motion request",
    falMotionInferenceDetail: "Fal motion inference",
    finalVideoDuration: "Длительность финального видео",
    sourceTitle: "Исходник",
    sourceInputLabel: "Input",
    dropzoneTitle: "Dropzone",
    addPetPhoto: "Добавьте фото питомца",
    dropzoneHint: "Нажмите на карточку или перетащите сюда изображение.",
    replaceHint: "Нажмите или перетащите для замены",
    uploadSupport: "Поддерживается image/* до 8 MB и drag-and-drop.",
    clear: "Очистить",
    noReference: "Без референса",
    inProgress: "В процессе",
    secondsSuffix: "сек",
    providerPendingAfterCompletion: "После завершения",
    providerPendingAfterGeneration: "После генерации",
    templateStatusActive: "Активен",
    templateStatusDraft: "Черновик",
    templateStatusArchived: "Архив",
    timelineTestQueued: "Тест поставлен в очередь",
    timelineTestQueuedDescription: "Создана админская тестовая задача без списания PawSpark.",
    timelinePhotoUploaded: "Фото загружено",
    timelinePhotoUploadedDescription:
      "Исходный файл принят системой и закреплён за запуском.",
    timelinePreprocessingStarted: "Препроцессинг запущен",
    timelineImageGenerationStarted: "Генерация изображения запущена",
    modelLabel: "Модель",
    timelinePreprocessingCompleted: "Препроцессинг завершён",
    timelineImageReceivedFromProvider: "Изображение получено от провайдера",
    timelineNormalizedImageReady: "Нормализованное изображение готово для генерации движения.",
    timelineGeneratedImageReady: "Итоговое изображение готово к импорту в media storage.",
    timelineMotionGeneration: "Генерация движения",
    timelineVideoReceivedFromProvider: "Видео получено от провайдера",
    timelineIntermediateVideoReady:
      "Промежуточный результат готов к импорту в media storage.",
    timelineMediaStorageImport: "Импорт в media storage",
    timelineFinalVideoSaved: "Финальное видео сохранено и доступно для проверки.",
    timelineFinalImageSaved: "Финальное изображение сохранено и доступно для проверки.",
    timelineCompletedSuccess: "Тест завершён успешно",
    timelineCompletedSuccessDescription: "Все артефакты доступны на этой странице.",
    timelineFailed: "Тест завершён с ошибкой",
    timelineFailedFallback: "Ошибка генерации",
    loadTemplateError: "Не удалось загрузить шаблон для теста.",
    refreshStatusError: "Не удалось обновить статус теста.",
  },
  en: {
    intlLocale: "en-US",
    fileFallback: "File",
    noPhotoSelected: "No photo selected",
    chooseImageFile: "Choose an image/* file",
    petMagicBilling: "PetMagic billing",
    falMotionCost: "Fal motion cost",
    falImageCost: "Fal image cost",
    falInference: "Fal inference time",
    falImageInference: "Fal image inference",
    waitingToStart: "Waiting to start",
    templateFallback: "Template",
    imageModelFallback: "Image model",
    stageOne: "Stage 01",
    stageTwo: "Stage 02",
    preprocessing: "Preprocessing",
    normalizedPhoto: "Normalized photo",
    preprocessingPending: "This frame will fill in as soon as preprocessing finishes.",
    preprocessingEmpty: "Upload a pet photo to prepare the frame for motion generation.",
    finalVideo: "Final video",
    finalImage: "Final image",
    result: "Result",
    readyVideo: "Ready video",
    readyImage: "Ready image",
    videoProcessing:
      "The video is being assembled. Preview and download will appear here after completion.",
    imageProcessing:
      "The image is being generated. Preview and download will appear here after completion.",
    videoReadyEmpty:
      "After generation, preview and download for the final video will always appear here.",
    imageReadyEmpty:
      "After generation, preview and download for the final image will appear here.",
    open: "Open",
    download: "Download",
    loadingWorkspace: "Loading test workspace...",
    templateNotFound: "Template was not found.",
    retry: "Retry",
    videoTemplates: "Video templates",
    imageTemplates: "Image templates",
    templateTest: "Template test",
    backToCatalog: "Back to catalog",
    openEditor: "Open editor",
    generationResult: "Generation result",
    launching: "Launching...",
    running: "Running...",
    generateTest: "Generate test",
    generationTime: "Generation time",
    lastUpdate: "Last update",
    generationEvents: "Generation events",
    done: "Done",
    runningShort: "Running",
    timelineEmpty: "Pipeline milestones appear here after the test starts.",
    runSummary: "Run summary",
    testHistory: "Test history",
    attempt: "Attempt",
    started: "Started",
    completed: "Completed",
    status: "Status",
    created: "Created",
    imageGenerationCompleted: "Image generation completed",
    falImageRequest: "Fal image request",
    falImageInferenceDetail: "Fal image inference",
    mediaImport: "Media import",
    failureCode: "Failure code",
    preprocessingCompleted: "Preprocessing completed",
    falPreprocessRequest: "Fal preprocess request",
    falPreprocessInference: "Fal preprocess inference",
    motionCompleted: "Motion completed",
    falMotionRequest: "Fal motion request",
    falMotionInferenceDetail: "Fal motion inference",
    finalVideoDuration: "Final video duration",
    sourceTitle: "Source",
    sourceInputLabel: "Input",
    dropzoneTitle: "Dropzone",
    addPetPhoto: "Add pet photo",
    dropzoneHint: "Click the card or drag an image here.",
    replaceHint: "Click or drag to replace",
    uploadSupport: "Supports image/* up to 8 MB and drag-and-drop.",
    clear: "Clear",
    noReference: "No reference",
    inProgress: "In progress",
    secondsSuffix: "sec",
    providerPendingAfterCompletion: "After completion",
    providerPendingAfterGeneration: "After generation",
    templateStatusActive: "Active",
    templateStatusDraft: "Draft",
    templateStatusArchived: "Archived",
    timelineTestQueued: "Test queued",
    timelineTestQueuedDescription: "A non-billed admin test job was created.",
    timelinePhotoUploaded: "Photo uploaded",
    timelinePhotoUploadedDescription: "The source file was accepted and attached to the run.",
    timelinePreprocessingStarted: "Preprocessing started",
    timelineImageGenerationStarted: "Image generation started",
    modelLabel: "Model",
    timelinePreprocessingCompleted: "Preprocessing completed",
    timelineImageReceivedFromProvider: "Image received from provider",
    timelineNormalizedImageReady: "The normalized image is ready for motion generation.",
    timelineGeneratedImageReady: "The generated image is ready for media storage import.",
    timelineMotionGeneration: "Motion generation",
    timelineVideoReceivedFromProvider: "Video received from provider",
    timelineIntermediateVideoReady:
      "The intermediate video is ready for media storage import.",
    timelineMediaStorageImport: "Media storage import",
    timelineFinalVideoSaved: "The final video was saved and is available for review.",
    timelineFinalImageSaved: "The final image was saved and is available for review.",
    timelineCompletedSuccess: "Test completed successfully",
    timelineCompletedSuccessDescription: "All generated artifacts are available on this page.",
    timelineFailed: "Test failed",
    timelineFailedFallback: "Generation failed",
    loadTemplateError: "Failed to load the template for testing.",
    refreshStatusError: "Failed to refresh test status.",
  },
} as const;

export type TemplateTestPageText = {
  [K in keyof (typeof templateTestPageText)["en"]]: (typeof templateTestPageText)["en"][K];
};

export function getTemplateTestPageText(locale: Locale): TemplateTestPageText {
  return templateTestPageText[locale] as TemplateTestPageText;
}
