import { type Locale } from "@/lib/i18n";

const templateAnalyticsCopy = {
  ru: {
    pageTitle: "Аналитика",
    videoTemplatesLabel: "Видео шаблоны",
    imageTemplatesLabel: "Шаблоны изображений",
    backToCatalog: "К каталогу",
    openEditor: "Открыть редактор",
    loading: "Загрузка аналитики шаблона...",
    loadError: "Не удалось загрузить аналитику шаблона.",
    secondaryPartialErrorTitle: "Часть аналитики временно недоступна",
    secondaryPartialErrorDescription:
      "Показываем доступные данные. Повторите загрузку, чтобы обновить недостающие блоки.",
    retryAction: "Повторить",
    rangeLabel: "Период аналитики",
    range7: "7 дней",
    range30: "30 дней",
    range90: "90 дней",
    rangeAll: "Всё время",
    comparePeriod: "Сравнить период",
    exportAnalytics: "Экспорт JSON",
    compareNoBase: "нет базы сравнения",
    templateOverviewTitle: "Карточка шаблона",
    templateIdLabel: "ID",
    categoryLabel: "Категория",
    priceLabel: "Доступ",
    tokenCostLabel: "Цена запуска",
    estimatedTemplateCostLabel: "Себестоимость, $",
    createdLabel: "Создан",
    publishedLabel: "Опубликован",
    updatedLabel: "Обновлён",
    totalRuns: "Всего запусков",
    successRate: "Успешность",
    completedRuns: "Успешные",
    failedRuns: "Ошибки",
    totalTokenCost: "Всего PawSpark",
    averageTokenCost: "Средняя стоимость",
    views: "Просмотры",
    viewsHint: "События view из публичного template endpoint.",
    generationStarts: "Запуски генерации",
    generationStartsHint: "Созданные задания генерации за выбранный период.",
    successfulGenerations: "Успешные генерации",
    successfulGenerationsHint: "Задания, завершённые готовым видео.",
    generationConversion: "Конверсия в результат",
    generationConversionHint: "Доля успешных jobs среди запусков.",
    tokenSpend: "Потрачено PawSpark",
    tokenSpendHint: "Суммарная стоимость запусков в PawSpark.",
    complaints: "Жалобы",
    complaintsHint: "События complaint из публичного analytics endpoint.",
    feedbackTitle: "Жалобы и фидбек",
    feedbackHint:
      "Последние обращения пользователей по шаблону: complaint и feedback события с текстом и метаданными.",
    feedbackFilterLabel: "Фильтр фидбека",
    feedbackFilterAll: "Все",
    feedbackFilterComplaint: "Жалобы",
    feedbackFilterFeedback: "Фидбек",
    feedbackSearchLabel: "Поиск по тексту фидбека",
    feedbackSearchPlaceholder: "Поиск по тексту сообщения",
    feedbackLoading: "Загрузка обращений...",
    feedbackEmpty: "Пока нет пользовательских жалоб или фидбека по этому шаблону.",
    feedbackFilteredEmpty: "По текущему фильтру и поиску ничего не найдено.",
    feedbackLoadError: "Не удалось загрузить жалобы и фидбек.",
    feedbackMessageMissing: "Без текста сообщения.",
    feedbackTypeComplaint: "Жалоба",
    feedbackTypeFeedback: "Фидбек",
    feedbackSourceLabel: "Источник",
    feedbackDeviceLabel: "Устройство",
    feedbackCountryLabel: "Страна",
    anonymousUser: "анон",
    feedbackSummaryTitle: "Сводка feedback",
    feedbackSummaryNegativeWarning: "У шаблона высокий негативный feedback.",
    feedbackSummaryDescription:
      "Сводка позитивных, нейтральных и негативных оценок по новому feedback.",
    feedbackSummaryPositive: "Позитив",
    feedbackSummaryNeutral: "Нейтрально",
    feedbackSummaryNegative: "Негатив",
    feedbackSummaryTopIssues: "Главные проблемы",
    activeQueue: "Активная очередь",
    runsLabel: "запусков",
    averageGenerationTime: "Среднее время",
    lastRun: "Последний запуск",
    lastCompleted: "Последний успех",
    snapshotTitle: "Сводка по шаблону",
    snapshotHint:
      "Этот блок собирается из существующей admin statistics модели и служит опорной сводкой для dashboard выше.",
    trendTitle: "Динамика запусков",
    trendHint: "Группировка generation jobs по дням создания шаблонных запусков.",
    trendEmpty: "Для этого шаблона ещё нет исторических точек тренда.",
    chartRuns: "Запуски",
    chartCompleted: "Успешные",
    chartFailed: "Ошибки",
    chartTokens: "PawSpark",
    chartDuration: "Время",
    statusBreakdownTitle: "Состояние пайплайна",
    statusBreakdownHint: "Распределение текущих и завершённых состояний генерации.",
    runsInQueue: "В очереди",
    processingNow: "В обработке",
    sourcesTitle: "Источники просмотров",
    sourcesHint: "Реальные source breakdown из template view events.",
    instrumentationPending:
      "Нужна запись событий в публичном приложении/API, чтобы показывать эти метрики без догадок.",
    retentionTitle: "Воронка генерации",
    retentionHint: "Реальная operational воронка по generation jobs.",
    funnelStarted: "Начали генерацию",
    funnelCompleted: "Дождались результата",
    funnelFailed: "Получили ошибку",
    funnelActive: "Ещё в работе",
    geographyTitle: "География пользователей",
    geographyHint: "Реальная география из событий public traffic, если страна была записана.",
    devicesTitle: "Устройства",
    devicesHint: "Реальное распределение устройств из записанных analytics events.",
    recentRunsTitle: "Последние генерации",
    recentRunsHint: "Последние задания по этому шаблону с минимальным operational срезом.",
    recentRunsAllHint:
      "Все доступные генерации по этому шаблону за весь период, который хранится в системе.",
    recentRunsLatest: "Последние",
    recentRunsAll: "Все генерации",
    recentRunsFailed: "Ошибочные",
    recentRunsLoading: "Загрузка...",
    recentRunsExpandError: "Не удалось загрузить полный список генераций.",
    recentRunsEmpty: "У шаблона пока нет недавних генераций.",
    failedRunsHint:
      "Все завершившиеся с ошибкой генерации по шаблону с кодом и текстом причины.",
    failedRunsEmpty: "По этому шаблону пока нет ошибочных генераций.",
    generationIdHeader: "ID генерации",
    userHeader: "Пользователь",
    recentCreated: "Создан",
    recentStatus: "Статус",
    recentTokens: "PawSpark",
    recentDuration: "Время",
    recentModels: "Модели",
    failureCodeHeader: "Код ошибки",
    failureReasonHeader: "Причина",
    recentOutput: "Выход",
    openOutput: "Открыть",
    outputAvailable: "Есть результат",
    noOutput: "Нет",
    failureBreakdownTitle: "Breakdown ошибок",
    failureBreakdownHint:
      "Сводка по failure codes из завершившихся с ошибкой generation jobs.",
    failuresEmpty: "Пока нет зарегистрированных ошибок по этому шаблону.",
    lastFailure: "Последняя",
    unknownFailure: "Неизвестная ошибка",
    preprocessingModel: "Image model",
    motionModel: "Motion model",
    noData:
      "У шаблона пока нет запусков. После первых генераций здесь появятся полноценные метрики.",
  },
  en: {
    pageTitle: "Analytics",
    videoTemplatesLabel: "Video templates",
    imageTemplatesLabel: "Image templates",
    backToCatalog: "Back to catalog",
    openEditor: "Open editor",
    loading: "Loading template analytics...",
    loadError: "Failed to load template analytics.",
    secondaryPartialErrorTitle: "Some analytics are temporarily unavailable",
    secondaryPartialErrorDescription:
      "Available data is still shown. Retry to refresh the missing sections.",
    retryAction: "Retry",
    rangeLabel: "Analytics period",
    range7: "7 days",
    range30: "30 days",
    range90: "90 days",
    rangeAll: "All time",
    comparePeriod: "Compare period",
    exportAnalytics: "Export JSON",
    compareNoBase: "no comparison base",
    templateOverviewTitle: "Template card",
    templateIdLabel: "ID",
    categoryLabel: "Category",
    priceLabel: "Access",
    tokenCostLabel: "Run price",
    estimatedTemplateCostLabel: "Provider cost, $",
    createdLabel: "Created",
    publishedLabel: "Published",
    updatedLabel: "Updated",
    totalRuns: "Total runs",
    successRate: "Success rate",
    completedRuns: "Completed",
    failedRuns: "Failed",
    totalTokenCost: "Total PawSpark cost",
    averageTokenCost: "Average PawSpark cost",
    views: "Views",
    viewsHint: "View events from the public template endpoint.",
    generationStarts: "Generation starts",
    generationStartsHint: "Generation jobs created in the selected period.",
    successfulGenerations: "Successful generations",
    successfulGenerationsHint: "Jobs completed with an output video.",
    generationConversion: "Result conversion",
    generationConversionHint: "Completed jobs as a share of started jobs.",
    tokenSpend: "PawSpark spend",
    tokenSpendHint: "Total PawSpark cost of runs.",
    complaints: "Complaints",
    complaintsHint: "Complaint events from the public analytics endpoint.",
    feedbackTitle: "Complaints and feedback",
    feedbackHint:
      "Latest user complaints and feedback for this template with message text and event metadata.",
    feedbackFilterLabel: "Feedback filter",
    feedbackFilterAll: "All",
    feedbackFilterComplaint: "Complaints",
    feedbackFilterFeedback: "Feedback",
    feedbackSearchLabel: "Search feedback text",
    feedbackSearchPlaceholder: "Search message text",
    feedbackLoading: "Loading feedback...",
    feedbackEmpty: "There is no user complaint or feedback for this template yet.",
    feedbackFilteredEmpty: "No items matched the current filter and search.",
    feedbackLoadError: "Failed to load complaints and feedback.",
    feedbackMessageMissing: "No message text provided.",
    feedbackTypeComplaint: "Complaint",
    feedbackTypeFeedback: "Feedback",
    feedbackSourceLabel: "Source",
    feedbackDeviceLabel: "Device",
    feedbackCountryLabel: "Country",
    anonymousUser: "guest",
    feedbackSummaryTitle: "Feedback summary",
    feedbackSummaryNegativeWarning: "This template has elevated negative feedback.",
    feedbackSummaryDescription: "Positive, neutral, and negative rate summary from the new feedback stream.",
    feedbackSummaryPositive: "Positive",
    feedbackSummaryNeutral: "Neutral",
    feedbackSummaryNegative: "Negative",
    feedbackSummaryTopIssues: "Top issues",
    activeQueue: "Active queue",
    runsLabel: "runs",
    averageGenerationTime: "Average generation time",
    lastRun: "Last run",
    lastCompleted: "Last completed",
    snapshotTitle: "Template snapshot",
    snapshotHint:
      "This block is built from the existing admin statistics model and acts as the anchor summary for the dashboard above.",
    trendTitle: "Run trend",
    trendHint: "Generation jobs grouped by creation day.",
    trendEmpty: "There are no trend points for this template yet.",
    chartRuns: "Runs",
    chartCompleted: "Completed",
    chartFailed: "Failed",
    chartTokens: "PawSpark",
    chartDuration: "Duration",
    statusBreakdownTitle: "Pipeline health",
    statusBreakdownHint: "Distribution of current and completed generation pipeline states.",
    runsInQueue: "Queued",
    processingNow: "Processing",
    sourcesTitle: "View sources",
    sourcesHint: "Real source breakdown from template view events.",
    instrumentationPending:
      "Public app/API instrumentation is required to show this without guessing.",
    retentionTitle: "Generation funnel",
    retentionHint: "Real operational funnel from generation jobs.",
    funnelStarted: "Started generation",
    funnelCompleted: "Completed result",
    funnelFailed: "Failed",
    funnelActive: "Still active",
    geographyTitle: "User geography",
    geographyHint: "Real geography from public traffic events when country was captured.",
    devicesTitle: "Devices",
    devicesHint: "Real device distribution from recorded analytics events.",
    recentRunsTitle: "Recent generations",
    recentRunsHint: "Latest jobs for this template with a compact operational snapshot.",
    recentRunsAllHint:
      "All available generations for this template across the full retained history.",
    recentRunsLatest: "Latest",
    recentRunsAll: "All generations",
    recentRunsFailed: "Failed only",
    recentRunsLoading: "Loading...",
    recentRunsExpandError: "Failed to load the full generation history.",
    recentRunsEmpty: "This template has no recent generations yet.",
    failedRunsHint: "All failed generations for this template with failure code and reason text.",
    failedRunsEmpty: "There are no failed generations for this template yet.",
    generationIdHeader: "Generation ID",
    userHeader: "User",
    recentCreated: "Created",
    recentStatus: "Status",
    recentTokens: "PawSpark",
    recentDuration: "Duration",
    recentModels: "Models",
    failureCodeHeader: "Failure code",
    failureReasonHeader: "Reason",
    recentOutput: "Output",
    openOutput: "Open",
    outputAvailable: "Available",
    noOutput: "None",
    failureBreakdownTitle: "Failure breakdown",
    failureBreakdownHint: "Summary of failure codes from failed generation jobs.",
    failuresEmpty: "There are no recorded failures for this template yet.",
    lastFailure: "Last",
    unknownFailure: "Unknown failure",
    preprocessingModel: "Image model",
    motionModel: "Motion model",
    noData:
      "This template has no runs yet. Full metrics will appear here after the first generations.",
  },
} as const;

export type TemplateAnalyticsCopy = {
  [K in keyof (typeof templateAnalyticsCopy)["en"]]: string;
};

export function getTemplateAnalyticsCopy(locale: Locale): TemplateAnalyticsCopy {
  return templateAnalyticsCopy[locale] as TemplateAnalyticsCopy;
}
