import { type Locale } from "@/lib/i18n";

const templatesAnalyticsHubPageText = {
  ru: {
    intlLocale: "ru-RU",
    eyebrow: "Интеллект шаблонов",
    title: "Аналитика шаблонов",
    description: "Общая статистика по просмотрам, генерациям, расходам и эффективности шаблонов.",
    catalog: "Каталог",
    export: "Экспорт",
    templates: "Шаблонов",
    video: "Видео",
    image: "Изображения",
    updated: "Обновлено",
    active: "Активные",
    premium: "Premium",
    free: "Бесплатно",
    loading: "Загрузка аналитики шаблонов...",
    loadError: "Не удалось загрузить аналитику шаблонов.",
    partialErrorTitle: "Отчет показан из последнего успешного ответа",
    partialErrorDescription:
      "Обновление аналитики не завершилось. Данные ниже остаются доступными.",
    retryAction: "Повторить",
    periodLabel: "Период",
    typeFilter: "Тип",
    categoryFilter: "Категория",
    statusFilter: "Статус",
    accessFilter: "Доступ",
    sortFilter: "Сортировка",
    allTemplates: "Все шаблоны",
    allCategories: "Все категории",
    allStatuses: "Все статусы",
    allAccess: "Все",
    draft: "Черновик",
    archived: "Архив",
    sortViews: "Просмотры",
    sortStarts: "Запуски",
    sortConversion: "Конверсия",
    sortCost: "Затраты",
    sortTokens: "PawSpark",
    sortUpdated: "Обновление",
    resetFilters: "Сбросить",
    exporting: "Подготовка...",
    exportError: "Не удалось подготовить полный экспорт. Повторите попытку.",
    views: "Просмотры шаблонов",
    viewsHint: "Просмотры всех выбранных шаблонов.",
    starts: "Запуски генераций",
    startsHint: "Запуски генерации за выбранный период.",
    completed: "Успешные генерации",
    completedHint: "Завершились готовым результатом.",
    conversion: "Конверсия в результат",
    conversionHint: "Успешные генерации от всех запусков.",
    tokens: "Потрачено PawSpark",
    tokensHint: "Суммарный расход пользователей на генерации.",
    providerSpend: "Наши затраты",
    providerSpendHint: "Реальные USD-затраты на AI-провайдера.",
    complaints: "Жалобы",
    complaintsHint: "Количество жалоб; ниже доступен список самих обращений.",
    feedbackTitle: "Жалобы и фидбек",
    feedbackHint:
      "Последние жалобы и фидбек по выбранным шаблонам с текстом сообщения и переходом в конкретный шаблон.",
    feedbackEmpty: "По выбранным фильтрам пока нет жалоб или фидбека.",
    feedbackMessageMissing: "Без текста сообщения.",
    feedbackTypeComplaint: "Жалоба",
    feedbackTypeFeedback: "Фидбек",
    feedbackSourceLabel: "Источник",
    feedbackDeviceLabel: "Устройство",
    feedbackCountryLabel: "Страна",
    feedbackUserLabel: "Пользователь",
    feedbackGenerationLabel: "Генерация",
    anonymousUser: "анон",
    chartViews: "Просмотры",
    chartStarts: "Запуски",
    chartCompleted: "Успех",
    chartCost: "Затраты",
    trendTitle: "Динамика по времени",
    trendHint: "Дневная динамика просмотров, запусков, успешных генераций и реальных затрат.",
    noTrend: "Пока нет точек тренда.",
    currentMetric: "Сумма выбранной метрики",
    funnelTitle: "Воронка конверсии",
    funnelHint: "От просмотра шаблона до результата и жалоб.",
    funnelViews: "Увидели шаблон",
    funnelStarts: "Запустили генерацию",
    funnelCompleted: "Получили результат",
    funnelFailed: "Получили ошибку",
    funnelComplaints: "Пожаловались",
    categoriesTitle: "Категории",
    categoriesHint: "Где концентрируются просмотры, запуски и расходы.",
    typesTitle: "Типы шаблонов",
    typesHint: "Видео и изображения в одной сводке.",
    sourcesTitle: "Источники просмотров",
    sourcesHint: "Откуда пользователи открывали выбранные шаблоны.",
    devicesTitle: "Устройства",
    devicesHint: "Классы устройств из публичной аналитики шаблонов.",
    geographyTitle: "География",
    geographyHint: "Страны из событий просмотра, без расчётных догадок.",
    startsShort: "запусков",
    topTitle: "Топ шаблонов",
    topHint: "Сортировка синхронизирована с выбранными фильтрами.",
    tableTitle: "Все шаблоны",
    tableHint: "Сводная таблица шаблонов по просмотрам, генерациям, ошибкам и реальным затратам.",
    templateCountLabel: "шаблонов",
    refreshing: "обновляется",
    templateColumn: "Шаблон",
    typeColumn: "Тип",
    categoryColumn: "Категория",
    statusColumn: "Статус",
    accessColumn: "Доступ",
    viewsColumn: "Просмотры",
    startsColumn: "Запуски",
    conversionColumn: "Конверсия",
    tokensColumn: "PawSpark",
    costColumn: "Затраты",
    actionsColumn: "Действия",
    openAnalytics: "Аналитика",
    openEditor: "Редактор",
    previousPage: "Назад",
    nextPage: "Далее",
    tableRange: "Показаны {from}–{to} из {total}",
    tableScrollHint: "Прокрутите таблицу по горизонтали, чтобы увидеть все показатели.",
    noRows: "Под выбранные фильтры шаблоны не найдены.",
  },
  en: {
    intlLocale: "en-US",
    eyebrow: "Template intelligence",
    title: "Template analytics",
    description: "Global view of template views, generations, spend, and performance.",
    catalog: "Catalog",
    export: "Export",
    templates: "Templates",
    video: "Video",
    image: "Images",
    updated: "Updated",
    active: "Active",
    premium: "Premium",
    free: "Free",
    loading: "Loading template analytics...",
    loadError: "Failed to load template analytics.",
    partialErrorTitle: "Showing the last successful report",
    partialErrorDescription:
      "Template analytics did not refresh. The report below is still available.",
    retryAction: "Retry",
    periodLabel: "Period",
    typeFilter: "Type",
    categoryFilter: "Category",
    statusFilter: "Status",
    accessFilter: "Access",
    sortFilter: "Sort",
    allTemplates: "All templates",
    allCategories: "All categories",
    allStatuses: "All statuses",
    allAccess: "All",
    draft: "Draft",
    archived: "Archived",
    sortViews: "Views",
    sortStarts: "Starts",
    sortConversion: "Conversion",
    sortCost: "Cost",
    sortTokens: "PawSpark",
    sortUpdated: "Updated",
    resetFilters: "Reset",
    exporting: "Preparing...",
    exportError: "Could not prepare the full export. Try again.",
    views: "Template views",
    viewsHint: "View events across selected templates.",
    starts: "Generation starts",
    startsHint: "Generation jobs created in the selected period.",
    completed: "Completed generations",
    completedHint: "Completed with an output result.",
    conversion: "Result conversion",
    conversionHint: "Completed jobs divided by starts.",
    tokens: "PawSpark spend",
    tokensHint: "Total user PawSpark spend for generations.",
    providerSpend: "Provider spend",
    providerSpendHint: "Real AI provider USD costs from jobs.",
    complaints: "Complaints",
    complaintsHint: "Complaint event count; see the feed below for actual messages.",
    feedbackTitle: "Complaints and feedback",
    feedbackHint:
      "Latest complaint and feedback events for the selected templates with message text and a link to the specific template.",
    feedbackEmpty: "There are no complaints or feedback items for the current filters yet.",
    feedbackMessageMissing: "No message text provided.",
    feedbackTypeComplaint: "Complaint",
    feedbackTypeFeedback: "Feedback",
    feedbackSourceLabel: "Source",
    feedbackDeviceLabel: "Device",
    feedbackCountryLabel: "Country",
    feedbackUserLabel: "User",
    feedbackGenerationLabel: "Generation",
    anonymousUser: "guest",
    chartViews: "Views",
    chartStarts: "Starts",
    chartCompleted: "Completed",
    chartCost: "Cost",
    trendTitle: "Trend over time",
    trendHint: "Daily trend for views, starts, completions, and real spend.",
    noTrend: "No trend points yet.",
    currentMetric: "Selected metric total",
    funnelTitle: "Conversion funnel",
    funnelHint: "From template view to result and complaints.",
    funnelViews: "Viewed template",
    funnelStarts: "Started generation",
    funnelCompleted: "Completed result",
    funnelFailed: "Failed",
    funnelComplaints: "Complaints",
    categoriesTitle: "Categories",
    categoriesHint: "Where views, starts, and spend concentrate.",
    typesTitle: "Template types",
    typesHint: "Video and Image in one overview.",
    sourcesTitle: "View sources",
    sourcesHint: "Real source events for selected templates.",
    devicesTitle: "Devices",
    devicesHint: "Device class from public analytics instrumentation.",
    geographyTitle: "Geography",
    geographyHint: "Country code from view events, without guessing.",
    startsShort: "starts",
    topTitle: "Top templates",
    topHint: "Sorted with the selected filters.",
    tableTitle: "All templates",
    tableHint: "Template table with views, generations, failures, and real provider costs.",
    templateCountLabel: "templates",
    refreshing: "refreshing",
    templateColumn: "Template",
    typeColumn: "Type",
    categoryColumn: "Category",
    statusColumn: "Status",
    accessColumn: "Access",
    viewsColumn: "Views",
    startsColumn: "Starts",
    conversionColumn: "Conversion",
    tokensColumn: "PawSpark",
    costColumn: "Cost",
    actionsColumn: "Actions",
    openAnalytics: "Analytics",
    openEditor: "Editor",
    previousPage: "Previous",
    nextPage: "Next",
    tableRange: "Showing {from}–{to} of {total}",
    tableScrollHint: "Scroll the table horizontally to view every metric.",
    noRows: "No templates match the selected filters.",
  },
} as const;

const templatesAnalyticsHubPeriodOptions = {
  ru: [
    { key: "7", label: "7 дней" },
    { key: "30", label: "30 дней" },
    { key: "90", label: "90 дней" },
    { key: "all", label: "Всё время" },
  ],
  en: [
    { key: "7", label: "7 days" },
    { key: "30", label: "30 days" },
    { key: "90", label: "90 days" },
    { key: "all", label: "All time" },
  ],
} as const;

export type TemplatesAnalyticsHubPageText = {
  [K in keyof (typeof templatesAnalyticsHubPageText)["en"]]: string;
};

export type TemplatesAnalyticsHubPeriodKey = "7" | "30" | "90" | "all";

export function getTemplatesAnalyticsHubPageText(locale: Locale): TemplatesAnalyticsHubPageText {
  return templatesAnalyticsHubPageText[locale] as TemplatesAnalyticsHubPageText;
}

export function getTemplatesAnalyticsHubPeriodOptions(locale: Locale): Array<{
  key: TemplatesAnalyticsHubPeriodKey;
  label: string;
}> {
  return [...templatesAnalyticsHubPeriodOptions[locale]];
}

export function getTemplatesAnalyticsHubIntlLocale(locale: Locale): string {
  return templatesAnalyticsHubPageText[locale].intlLocale;
}
