import { type Locale } from "@/lib/i18n";

export const ledgerSourceOptions = {
  ru: [
    { value: "", label: "Все источники" },
    { value: "pack_purchase", label: "Покупка пакета" },
    { value: "generation_spend", label: "Списание за генерацию" },
    { value: "weekly_grant", label: "Недельная награда" },
    { value: "ad_reward", label: "Награда за рекламу" },
    { value: "redeem_code", label: "Промокод" },
    { value: "premium_subscription_grant", label: "Выдача Premium PawSpark" },
    { value: "admin_grant", label: "Ручное начисление" },
    { value: "admin_debit", label: "Ручное списание" },
  ],
  en: [
    { value: "", label: "All sources" },
    { value: "pack_purchase", label: "Pack purchase" },
    { value: "generation_spend", label: "Generation spend" },
    { value: "weekly_grant", label: "Weekly reward" },
    { value: "ad_reward", label: "Ad reward" },
    { value: "redeem_code", label: "Redeem code" },
    { value: "premium_subscription_grant", label: "Premium PawSpark grant" },
    { value: "admin_grant", label: "Manual grant" },
    { value: "admin_debit", label: "Manual debit" },
  ],
} as const;

export const purchaseStatusOptions = {
  ru: [
    { value: "", label: "Все статусы" },
    { value: "pending", label: "Ожидает" },
    { value: "succeeded", label: "Успешно" },
    { value: "failed", label: "Ошибка" },
    { value: "refunded", label: "Возврат" },
  ],
  en: [
    { value: "", label: "All statuses" },
    { value: "pending", label: "Pending" },
    { value: "succeeded", label: "Succeeded" },
    { value: "failed", label: "Failed" },
    { value: "refunded", label: "Refunded" },
  ],
} as const;

export const subscriptionProviderOptions = {
  ru: [
    { value: "", label: "Все провайдеры" },
    { value: "app_store", label: "Apple App Store" },
    { value: "google_play", label: "Google Play" },
    { value: "stripe", label: "Stripe" },
  ],
  en: [
    { value: "", label: "All providers" },
    { value: "app_store", label: "Apple App Store" },
    { value: "google_play", label: "Google Play" },
    { value: "stripe", label: "Stripe" },
  ],
} as const;

export const subscriptionStatusOptions = {
  ru: [
    { value: "", label: "Все статусы" },
    { value: "active", label: "Активна" },
    { value: "trialing", label: "Пробный период" },
    { value: "past_due", label: "Просрочка" },
    { value: "canceled", label: "Отменена" },
    { value: "expired", label: "Истекла" },
  ],
  en: [
    { value: "", label: "All statuses" },
    { value: "active", label: "Active" },
    { value: "trialing", label: "Trialing" },
    { value: "past_due", label: "Past due" },
    { value: "canceled", label: "Canceled" },
    { value: "expired", label: "Expired" },
  ],
} as const;

export const eventStatusOptions = {
  ru: [
    { value: "", label: "Все статусы" },
    { value: "active", label: "Активна" },
    { value: "canceled", label: "Отменена" },
    { value: "expired", label: "Истекла" },
    { value: "processed", label: "Обработано" },
    { value: "failed", label: "Ошибка" },
  ],
  en: [
    { value: "", label: "All statuses" },
    { value: "active", label: "Active" },
    { value: "canceled", label: "Canceled" },
    { value: "expired", label: "Expired" },
    { value: "processed", label: "Processed" },
    { value: "failed", label: "Failed" },
  ],
} as const;

export const incidentStatusOptions = {
  ru: [
    { value: "open", label: "Открытые" },
    { value: "resolved", label: "Закрытые" },
    { value: "", label: "Все" },
  ],
  en: [
    { value: "open", label: "Open" },
    { value: "resolved", label: "Resolved" },
    { value: "", label: "All" },
  ],
} as const;

export const incidentCategoryOptions = {
  ru: [
    { value: "", label: "Все категории" },
    { value: "pending", label: "Pending" },
    { value: "failed", label: "Failed" },
    { value: "disputed", label: "Disputed" },
    { value: "refund_pending", label: "Refund pending" },
    { value: "settlement_failed", label: "Settlement failed" },
    { value: "webhook_failed", label: "Webhook failed" },
    { value: "reconciliation_required", label: "Нужна reconciliation" },
    { value: "manual_review_required", label: "Ручная проверка" },
    { value: "resolved", label: "Resolved" },
  ],
  en: [
    { value: "", label: "All categories" },
    { value: "pending", label: "Pending" },
    { value: "failed", label: "Failed" },
    { value: "disputed", label: "Disputed" },
    { value: "refund_pending", label: "Refund pending" },
    { value: "settlement_failed", label: "Settlement failed" },
    { value: "webhook_failed", label: "Webhook failed" },
    { value: "reconciliation_required", label: "Reconciliation required" },
    { value: "manual_review_required", label: "Manual review required" },
    { value: "resolved", label: "Resolved" },
  ],
} as const;

const economyText = {
  ru: {
    intlLocale: "ru-RU",
      eyebrow: "Экономика и кошелек",
      title: "Экономика",
      description:
        "Общий обзор движения валюты, платежных статусов и пакетов пополнения без ухода в карточки пользователей.",
      loadingTitle: "Загружаем экономику",
      loadingDescription: "Подтягиваем историю операций, покупки и конфигурацию пакетов.",
      errorTitle: "Не удалось загрузить экономику",
      errorDescription: "Проверьте доступ к сервису и повторите запрос.",
      partialErrorTitle: "Часть данных не обновилась",
      retry: "Повторить",
      metaPacks: "Пакетов",
      metaLedger: "Операций",
      metaPurchases: "Покупок",
      metaSubscriptions: "Подписок",
      metaRoutes: "Маршрутов",
      activePacksLabel: "Активные паки",
      creditFlowLabel: "Начисления",
      debitFlowLabel: "Списания",
      revenueLabel: "Выручка",
      activeSubscriptionsLabel: "Активные подписки",
      renewalStopsLabel: "Остановки продления",
      activePlansCountLabel: "Активные планы",
      enabledRoutesLabel: "Включенные маршруты",
      openIncidentsLabel: "Открытые incidents",
      packsTitle: "Паки пополнения",
      packsDescription:
        "Редактирование цен, бонуса и видимости пакетов без затрагивания истории покупок.",
      subscriptionPlansTitle: "Premium планы",
      subscriptionPlansDescription:
        "Текущая конфигурация месячных и годовых планов, которую видят мобильный клиент и экран оплаты.",
      providerConfigsTitle: "Маршрутизация платежей",
      providerConfigsDescription:
        "Серверные правила выбора App Store, Google Play и Stripe по платформе и региону.",
      providerConfigCreateTitle: "Создать маршрут",
      providerConfigCreateAction: "Добавить маршрут",
      providerConfigTestTitle: "Проверка маршрута",
      providerConfigTestAction: "Проверить маршрут",
      providerConfigMatchLabel: "Сработавший маршрут",
      providerConfigNoMatchLabel: "Совпадений нет для указанных входных условий.",
      providerCodePlaceholder: "stripe",
      platformCodePlaceholder: "web",
      providerRegionPlaceholder: "US или *",
      providerModePlaceholder: "live",
      providerAppVersionPlaceholder: "1.0.0",
      providerBonusPlaceholder: "0",
      subscriptionsTitle: "Активные и недавние подписки",
      subscriptionsDescription:
        "Снимок последних premium подписок по пользователям с провайдером, PawSpark и датой продления.",
      subscriptionEventsTitle: "Лог событий подписок",
      subscriptionEventsDescription:
        "Последние события жизненного цикла из магазинов приложений и Stripe для диагностики интеграции.",
      incidentsTitle: "Payment incidents",
      incidentsDescription:
        "Очередь спорных состояний: зависшие заказы, расхождения ledger, premium и webhooks.",
      incidentStatusFilterLabel: "Incident статус",
      incidentCategoryFilterLabel: "Категория",
      incidentTypeFilterLabel: "Тип incident",
      incidentTypePlaceholder: "PremiumEntitlementMismatch",
      runReconciliationAction: "Запустить reconciliation",
      resolveIncidentAction: "Закрыть",
      reopenIncidentAction: "Переоткрыть",
      viewIncidentAction: "Детали",
      incidentActionLabel: "Операторское действие",
      incidentReasonLabel: "Причина",
      incidentAmountLabel: "Сумма PawSpark",
      incidentExternalReferenceLabel: "External refund/event id",
      incidentActionSubmit: "Выполнить действие",
      incidentActionSuccess: "Действие выполнено.",
      incidentActionError: "Не удалось выполнить действие.",
      incidentReasonRequired: "Укажите причину действия.",
      incidentDetailTitle: "Incident detail",
      incidentLinksTitle: "Связи",
      incidentWebhookTitle: "Webhook snapshot",
      incidentAuditTitle: "Audit trail",
      incidentLedgerTitle: "Связанный ledger",
      incidentWalletTitle: "Wallet",
      incidentGenerationTitle: "Генерация",
      incidentNoDetail: "Выберите incident для диагностики.",
      incidentNoAudit: "История действий пока пуста.",
      incidentSafePayloadLabel: "Safe payload snapshot",
      reconciliationStarted: "Reconciliation выполнен.",
      reconciliationFailed: "Не удалось выполнить reconciliation.",
      incidentResolved: "Incident закрыт.",
      incidentResolveError: "Не удалось закрыть incident.",
      noIncidents: "Открытых payment incidents нет.",
      tokensShort: "PawSpark",
      packSaved: "Пакет обновлен.",
      packSaveError: "Не удалось сохранить пакет.",
      planSaved: "Premium план обновлен.",
      planSaveError: "Не удалось сохранить Premium план.",
      providerConfigSaved: "Маршрут оплаты обновлен.",
      providerConfigSaveError: "Не удалось сохранить маршрут оплаты.",
      providerConfigCreated: "Маршрут оплаты создан.",
      providerConfigCreateError: "Не удалось создать маршрут оплаты.",
      providerConfigCloned: "Маршрут оплаты клонирован.",
      providerConfigCloneError: "Не удалось клонировать маршрут оплаты.",
      providerConfigDeleted: "Маршрут оплаты удален.",
      providerConfigDeleteError: "Не удалось удалить маршрут оплаты.",
      providerConfigTestError: "Не удалось проверить маршрут оплаты.",
      packMissingDraft: "Пакет не найден в текущем списке.",
      planMissingDraft: "План не найден в текущем списке.",
      providerConfigMissingDraft: "Маршрут оплаты не найден в текущем списке.",
      invalidPackNumbers: "Укажите корректные название, цену, PawSpark и порядок пакета.",
      invalidPlanNumbers: "Укажите корректные цену, валюту и лимит PawSpark для плана.",
      invalidProviderConfig:
        "Заполните регион, минимальную версию приложения, режим маршрута и бонус от 0 до 100%.",
      invalidProviderConfigCreate: "Укажите провайдера и платформу для нового маршрута.",
      invalidProviderConfigMatch:
        "Укажите провайдера, платформу, регион и версию приложения для проверки маршрута.",
      packColumn: "Пакет",
      planColumn: "План",
      priceColumn: "Цена",
      grantedColumn: "База",
      bonusColumn: "Бонус",
      sortColumn: "Порядок",
      activeColumn: "Активен",
      actionsColumn: "Действие",
      activeState: "Включен",
      inactiveState: "Скрыт",
      recommendedState: "Рекомендуем",
      savingAction: "Сохраняем...",
      saveAction: "Сохранить",
      noPacks: "Паки пополнения пока не настроены.",
      noSubscriptionPlans: "Premium планы пока не настроены.",
      noProviderConfigs: "Правила маршрутизации платежей пока не настроены.",
      noSubscriptions: "Подписки пока не найдены.",
      noSubscriptionEvents: "События подписок пока не записаны.",
      noDescription: "Без описания",
      ledgerTitle: "Журнал операций",
      ledgerDescription:
        "Последние движения баланса по всем пользователям с источником и причиной.",
      ledgerFilterLabel: "Источник",
      purchaseFilterLabel: "Статус",
      purchaseProviderFilterLabel: "Провайдер",
      searchFilterLabel: "Поиск",
      purchaseSearchPlaceholder: "order id, user id или пакет",
      subscriptionSearchPlaceholder: "subscription id, user id или план",
      previousPage: "Назад",
      nextPage: "Вперед",
      previousLedgerPageLabel: "Предыдущая страница журнала",
      nextLedgerPageLabel: "Следующая страница журнала",
      previousPurchasesPageLabel: "Предыдущая страница покупок",
      nextPurchasesPageLabel: "Следующая страница покупок",
      previousSubscriptionsPageLabel: "Предыдущая страница подписок",
      nextSubscriptionsPageLabel: "Следующая страница подписок",
      cancelSubscriptionAction: "Отменить",
      cancelSubscriptionTitle: "Отменить подписку?",
      cancelSubscriptionDescription:
        "Premium будет отозван сразу, подписка Stripe будет отменена, действие попадет в журнал аудита.",
      cancelSubscriptionSuccess: "Подписка отменена.",
      cancelSubscriptionError: "Не удалось отменить подписку.",
      refundPurchaseAction: "Вернуть",
      refundPurchaseTitle: "Вернуть платеж?",
      refundPurchaseDescription:
        "Stripe выполнит полный возврат покупки, статус заказа сменится на возврат, действие попадет в журнал аудита.",
      refundPurchaseSuccess: "Платеж возвращен.",
      refundPurchaseError: "Не удалось вернуть платеж.",
      confirmationCancel: "Отмена",
      noLedger: "Операций пока нет.",
      purchasesTitle: "Покупки и статусы",
      purchasesDescription: "Последние заказы с итоговым статусом оплаты и начислением PawSpark.",
      noPurchases: "Покупок пока нет.",
      timeColumn: "Время",
      userColumn: "Пользователь",
      deltaColumn: "Изменение",
      balanceColumn: "Баланс",
      sourceColumn: "Источник",
      tokenKindColumn: "Тип токенов",
      operationKindColumn: "Операция",
      expiryColumn: "Expiry",
      bucketAllocationColumn: "Buckets",
      reasonColumn: "Причина",
      amountColumn: "Сумма",
      statusColumn: "Статус",
      severityColumn: "Важность",
      incidentColumn: "Incident",
      categoryColumn: "Категория",
      retryColumn: "Retry",
      billingColumn: "Период",
      tokensColumn: "Лимит PawSpark",
      providerColumn: "Провайдер",
      productTypeColumn: "Тип продукта",
      refundStatusColumn: "Возврат",
      platformColumn: "Платформа",
      regionColumn: "Регион",
      productIdsColumn: "ID продуктов",
      appleProductLabel: "Apple product ID",
      googleProductLabel: "Google product ID",
      stripePriceLabel: "Stripe price ID",
      flagsColumn: "Флаги",
      modeColumn: "Режим",
      notesLabel: "Заметки",
      renewalColumn: "Следующее списание",
      eventTypeColumn: "Событие",
      processedColumn: "Обработано",
      cancelAtPeriodEndLabel: "Без автопродления",
      externalCheckoutFlag: "Внешняя оплата",
      recommendedFlag: "Рекомендуемый",
      defaultFlag: "По умолчанию",
      externalWarningFlag: "Внешнее предупреждение",
      storeDisclosureFlag: "Раскрытие условий магазина",
      minVersionLabel: "Минимум",
      bonusPercentLabel: "Бонус, %",
      displayLabelLabel: "Название",
      displaySubtitleLabel: "Подзаголовок",
      warningTitleLabel: "Заголовок предупреждения",
      warningMessageLabel: "Текст предупреждения",
      cloneRegionPlaceholder: "Регион для копии",
      cloneAction: "Клонировать",
      deleteAction: "Удалить",
      providerConfigDeleteConfirm: "Удалить этот маршрут оплаты?",
      financialActionsAdminOnly: "Финансовые действия доступны только Admin.",
      notProcessedLabel: "Еще не обработано",
      watermarkTitle: "Watermark",
      watermarkDescription:
        "Настройки мягкого продвижения для бесплатных результатов и разового clean unlock.",
      saveWatermarkAction: "Сохранить watermark",
      watermarkLoadingTitle: "Загружаем watermark",
      watermarkSettingsNotLoaded: "Настройки watermark не загружены",
      watermarkSaved: "Настройки watermark сохранены",
      watermarkSaveError: "Не удалось сохранить watermark",
      watermarkEnabledState: "Включён",
      watermarkDisabledState: "Отключён",
      watermarkImagesLabel: "Images",
      watermarkVideosLabel: "Videos",
      watermarkTextLabel: "Текст",
      watermarkCostCreditsLabel: "Cost in credits",
      watermarkOpacityLabel: "Opacity",
      watermarkLogoUrlLabel: "Logo URL",
      watermarkPositionLabel: "Position",
      watermarkSizeLabel: "Size",
      watermarkPreviewImageTitle: "Preview image",
      watermarkPreviewVideoFrameTitle: "Preview video frame",
      watermarkPreviewTestImage: "Тестовое изображение",
      watermarkPreviewTestVideoFrame: "Тестовый кадр видео",
    },
  en: {
    intlLocale: "en-US",
    eyebrow: "Economy and wallet",
    title: "Economy",
    description:
      "System-wide view of balance movement, payment statuses, and top-up packs without opening each user profile.",
    loadingTitle: "Loading economy",
    loadingDescription: "Fetching ledger, purchases, and pack configuration.",
    errorTitle: "Failed to load economy",
    errorDescription: "Check service availability and try again.",
    partialErrorTitle: "Some data did not refresh",
    retry: "Retry",
    metaPacks: "Packs",
    metaLedger: "Ledger rows",
    metaPurchases: "Purchases",
    metaSubscriptions: "Subscriptions",
    metaRoutes: "Routes",
    activePacksLabel: "Active packs",
    creditFlowLabel: "Credits",
    debitFlowLabel: "Debits",
    revenueLabel: "Revenue",
    activeSubscriptionsLabel: "Active subscriptions",
    renewalStopsLabel: "Renewal stops",
    activePlansCountLabel: "Active plans",
    enabledRoutesLabel: "Enabled routes",
    openIncidentsLabel: "Open incidents",
    packsTitle: "Top-up packs",
    packsDescription:
      "Update pricing, bonus, and visibility without touching historical purchases.",
    subscriptionPlansTitle: "Premium plans",
    subscriptionPlansDescription:
      "Current monthly and yearly plan configuration used by mobile clients and checkout flows.",
    providerConfigsTitle: "Payment routing",
    providerConfigsDescription:
      "Backend-controlled rules that choose App Store, Google Play, and Stripe by platform and region.",
    providerConfigCreateTitle: "Create route",
    providerConfigCreateAction: "Add route",
    providerConfigTestTitle: "Route check",
    providerConfigTestAction: "Check route",
    providerConfigMatchLabel: "Matched route",
    providerConfigNoMatchLabel: "No route matched the provided input conditions.",
    providerCodePlaceholder: "stripe",
    platformCodePlaceholder: "web",
    providerRegionPlaceholder: "US or *",
    providerModePlaceholder: "live",
    providerAppVersionPlaceholder: "1.0.0",
    providerBonusPlaceholder: "0",
    subscriptionsTitle: "Active and recent subscriptions",
    subscriptionsDescription:
      "Snapshot of recent premium subscriptions with provider, PawSpark usage, and renewal date.",
    subscriptionEventsTitle: "Subscription event log",
    subscriptionEventsDescription:
      "Recent lifecycle events from store and Stripe flows for integration diagnostics.",
    incidentsTitle: "Payment incidents",
    incidentsDescription:
      "Review queue for stuck orders, ledger mismatches, premium drift, and webhook anomalies.",
    incidentStatusFilterLabel: "Incident status",
    incidentCategoryFilterLabel: "Category",
    incidentTypeFilterLabel: "Incident type",
    incidentTypePlaceholder: "PremiumEntitlementMismatch",
    runReconciliationAction: "Run reconciliation",
    resolveIncidentAction: "Resolve",
    reopenIncidentAction: "Reopen",
    viewIncidentAction: "Details",
    incidentActionLabel: "Operator action",
    incidentReasonLabel: "Reason",
    incidentAmountLabel: "PawSpark amount",
    incidentExternalReferenceLabel: "External refund/event id",
    incidentActionSubmit: "Run action",
    incidentActionSuccess: "Action completed.",
    incidentActionError: "Failed to run action.",
    incidentReasonRequired: "Enter an action reason.",
    incidentDetailTitle: "Incident detail",
    incidentLinksTitle: "Links",
    incidentWebhookTitle: "Webhook snapshot",
    incidentAuditTitle: "Audit trail",
    incidentLedgerTitle: "Related ledger",
    incidentWalletTitle: "Wallet",
    incidentGenerationTitle: "Generation",
    incidentNoDetail: "Select an incident to inspect.",
    incidentNoAudit: "No operator actions recorded yet.",
    incidentSafePayloadLabel: "Safe payload snapshot",
    reconciliationStarted: "Reconciliation completed.",
    reconciliationFailed: "Failed to run reconciliation.",
    incidentResolved: "Incident resolved.",
    incidentResolveError: "Failed to resolve incident.",
    noIncidents: "No open payment incidents.",
    tokensShort: "spark",
    packSaved: "Pack updated.",
    packSaveError: "Failed to save pack.",
    planSaved: "Premium plan updated.",
    planSaveError: "Failed to save premium plan.",
    providerConfigSaved: "Payment route updated.",
    providerConfigSaveError: "Failed to save payment route.",
    providerConfigCreated: "Payment route created.",
    providerConfigCreateError: "Failed to create payment route.",
    providerConfigCloned: "Payment route cloned.",
    providerConfigCloneError: "Failed to clone payment route.",
    providerConfigDeleted: "Payment route deleted.",
    providerConfigDeleteError: "Failed to delete payment route.",
    providerConfigTestError: "Failed to check payment route.",
    packMissingDraft: "Pack was not found in the current list.",
    planMissingDraft: "Premium plan was not found in the current list.",
    providerConfigMissingDraft: "Payment route was not found in the current list.",
    invalidPackNumbers: "Enter a valid pack name, price, PawSpark amounts, and sort order.",
    invalidPlanNumbers: "Enter a valid price, currency, and PawSpark limit for the plan.",
    invalidProviderConfig:
      "Enter a valid region, minimum app version, routing mode, and 0-100% bonus.",
    invalidProviderConfigCreate: "Enter provider and platform for the new route.",
    invalidProviderConfigMatch: "Enter provider/platform/region/appVersion for route check.",
    packColumn: "Pack",
    planColumn: "Plan",
    priceColumn: "Price",
    grantedColumn: "Base",
    bonusColumn: "Bonus",
    sortColumn: "Sort",
    activeColumn: "Active",
    actionsColumn: "Action",
    activeState: "On",
    inactiveState: "Hidden",
    recommendedState: "Recommended",
    savingAction: "Saving...",
    saveAction: "Save",
    noPacks: "No top-up packs configured yet.",
    noSubscriptionPlans: "No premium plans configured yet.",
    noProviderConfigs: "No payment routing rules configured yet.",
    noSubscriptions: "No subscriptions found yet.",
    noSubscriptionEvents: "No subscription events recorded yet.",
    noDescription: "No description",
    ledgerTitle: "Wallet ledger",
    ledgerDescription: "Recent balance movements across users with source and reason.",
    ledgerFilterLabel: "Source",
    purchaseFilterLabel: "Status",
    purchaseProviderFilterLabel: "Provider",
    searchFilterLabel: "Search",
    purchaseSearchPlaceholder: "order id, user id, or pack",
    subscriptionSearchPlaceholder: "subscription id, user id, or plan",
    previousPage: "Previous",
    nextPage: "Next",
    previousLedgerPageLabel: "Previous ledger page",
    nextLedgerPageLabel: "Next ledger page",
    previousPurchasesPageLabel: "Previous purchases page",
    nextPurchasesPageLabel: "Next purchases page",
    previousSubscriptionsPageLabel: "Previous subscriptions page",
    nextSubscriptionsPageLabel: "Next subscriptions page",
    cancelSubscriptionAction: "Cancel",
    cancelSubscriptionTitle: "Cancel subscription?",
    cancelSubscriptionDescription:
      "Premium will be revoked immediately, the Stripe subscription will be canceled, and the action will be written to audit log.",
    cancelSubscriptionSuccess: "Subscription canceled.",
    cancelSubscriptionError: "Failed to cancel subscription.",
    refundPurchaseAction: "Refund",
    refundPurchaseTitle: "Refund payment?",
    refundPurchaseDescription:
      "A full Stripe refund will be created, the order status will become refunded, and the action will be written to audit log.",
    refundPurchaseSuccess: "Payment refunded.",
    refundPurchaseError: "Failed to refund payment.",
    confirmationCancel: "Cancel",
    noLedger: "No wallet operations yet.",
    purchasesTitle: "Purchases and statuses",
    purchasesDescription: "Recent orders with payment outcome and spark grant value.",
    noPurchases: "No purchases yet.",
    timeColumn: "Time",
    userColumn: "User",
    deltaColumn: "Delta",
    balanceColumn: "Balance",
    sourceColumn: "Source",
    tokenKindColumn: "Token kind",
    operationKindColumn: "Operation",
    expiryColumn: "Expiry",
    bucketAllocationColumn: "Buckets",
    reasonColumn: "Reason",
    amountColumn: "Amount",
    statusColumn: "Status",
    severityColumn: "Severity",
    incidentColumn: "Incident",
    categoryColumn: "Category",
    retryColumn: "Retry",
    billingColumn: "Period",
    tokensColumn: "PawSpark limit",
    providerColumn: "Provider",
    productTypeColumn: "Product type",
    refundStatusColumn: "Refund",
    platformColumn: "Platform",
    regionColumn: "Region",
    productIdsColumn: "Store IDs",
    appleProductLabel: "Apple product ID",
    googleProductLabel: "Google product ID",
    stripePriceLabel: "Stripe price ID",
    flagsColumn: "Flags",
    modeColumn: "Mode",
    notesLabel: "Notes",
    renewalColumn: "Next renewal",
    eventTypeColumn: "Event",
    processedColumn: "Processed",
    cancelAtPeriodEndLabel: "No auto-renew",
    externalCheckoutFlag: "External checkout",
    recommendedFlag: "Recommended",
    defaultFlag: "Default",
    externalWarningFlag: "External warning",
    storeDisclosureFlag: "Store disclosure",
    minVersionLabel: "Min",
    bonusPercentLabel: "Bonus, %",
    displayLabelLabel: "Label",
    displaySubtitleLabel: "Subtitle",
    warningTitleLabel: "Warning title",
    warningMessageLabel: "Warning message",
    cloneRegionPlaceholder: "Clone region",
    cloneAction: "Clone",
    deleteAction: "Delete",
    providerConfigDeleteConfirm: "Delete this payment route?",
    financialActionsAdminOnly: "Financial actions are available to Admin only.",
    notProcessedLabel: "Not processed yet",
    watermarkTitle: "Watermark",
    watermarkDescription:
      "Free-result promotion and one-time clean unlock settings.",
    saveWatermarkAction: "Save watermark",
    watermarkLoadingTitle: "Loading watermark settings",
    watermarkSettingsNotLoaded: "Watermark settings are not loaded",
    watermarkSaved: "Watermark settings saved",
    watermarkSaveError: "Could not save watermark settings",
    watermarkEnabledState: "Enabled",
    watermarkDisabledState: "Disabled",
    watermarkImagesLabel: "Images",
    watermarkVideosLabel: "Videos",
    watermarkTextLabel: "Text",
    watermarkCostCreditsLabel: "Cost in credits",
    watermarkOpacityLabel: "Opacity",
    watermarkLogoUrlLabel: "Logo URL",
    watermarkPositionLabel: "Position",
    watermarkSizeLabel: "Size",
    watermarkPreviewImageTitle: "Preview image",
    watermarkPreviewVideoFrameTitle: "Preview video frame",
    watermarkPreviewTestImage: "Test image",
    watermarkPreviewTestVideoFrame: "Test video frame",
  },
} as const;

export type EconomyPageText = { [K in keyof (typeof economyText)["en"]]: string };

export function getEconomyText(locale: Locale): EconomyPageText {
  return economyText[locale] as EconomyPageText;
}
