import { type Locale } from "@/lib/i18n";

export const ledgerSourceOptions = {
  ru: [
    { value: "", label: "Все источники" },
    { value: "pack_purchase", label: "Покупка пакета" },
    { value: "generation_spend", label: "Списание за генерацию" },
    { value: "weekly_grant", label: "Недельная награда" },
    { value: "ad_reward", label: "Награда за рекламу" },
    { value: "redeem_code", label: "Промокод" },
    { value: "premium_subscription_grant", label: "Выдача Premium токенов" },
    { value: "admin_grant", label: "Ручное начисление" },
    { value: "admin_debit", label: "Ручное списание" },
  ],
  en: [
    { value: "", label: "All sources" },
    { value: "pack_purchase", label: "Pack purchase" },
    { value: "generation_spend", label: "Generation spend" },
    { value: "weekly_grant", label: "Weekly reward" },
    { value: "ad_reward", label: "Ad reward" },
    { value: "redeem_code", label: "Redeem code" },
    { value: "premium_subscription_grant", label: "Premium token grant" },
    { value: "admin_grant", label: "Manual grant" },
    { value: "admin_debit", label: "Manual debit" },
  ],
} as const;

export const purchaseStatusOptions = {
  ru: [
    { value: "", label: "Все статусы" },
    { value: "pending", label: "Ожидает" },
    { value: "succeeded", label: "Успешно" },
    { value: "failed", label: "Ошибка" },
  ],
  en: [
    { value: "", label: "All statuses" },
    { value: "pending", label: "Pending" },
    { value: "succeeded", label: "Succeeded" },
    { value: "failed", label: "Failed" },
  ],
} as const;

export const subscriptionProviderOptions = {
  ru: [
    { value: "", label: "Все провайдеры" },
    { value: "app_store", label: "Apple App Store" },
    { value: "google_play", label: "Google Play" },
    { value: "stripe", label: "Stripe" },
  ],
  en: [
    { value: "", label: "All providers" },
    { value: "app_store", label: "Apple App Store" },
    { value: "google_play", label: "Google Play" },
    { value: "stripe", label: "Stripe" },
  ],
} as const;

export const subscriptionStatusOptions = {
  ru: [
    { value: "", label: "Все статусы" },
    { value: "active", label: "Активна" },
    { value: "trialing", label: "Пробный период" },
    { value: "past_due", label: "Просрочка" },
    { value: "canceled", label: "Отменена" },
    { value: "expired", label: "Истекла" },
  ],
  en: [
    { value: "", label: "All statuses" },
    { value: "active", label: "Active" },
    { value: "trialing", label: "Trialing" },
    { value: "past_due", label: "Past due" },
    { value: "canceled", label: "Canceled" },
    { value: "expired", label: "Expired" },
  ],
} as const;

export const eventStatusOptions = {
  ru: [
    { value: "", label: "Все статусы" },
    { value: "active", label: "Активна" },
    { value: "canceled", label: "Отменена" },
    { value: "expired", label: "Истекла" },
    { value: "processed", label: "Обработано" },
    { value: "failed", label: "Ошибка" },
  ],
  en: [
    { value: "", label: "All statuses" },
    { value: "active", label: "Active" },
    { value: "canceled", label: "Canceled" },
    { value: "expired", label: "Expired" },
    { value: "processed", label: "Processed" },
    { value: "failed", label: "Failed" },
  ],
} as const;

export function getEconomyText(locale: Locale) {
  if (locale === "ru") {
    return {
      eyebrow: "Экономика и кошелек",
      title: "Экономика",
      description:
        "Общий обзор движения валюты, платежных статусов и пакетов пополнения без ухода в карточки пользователей.",
      loadingTitle: "Загружаем экономику",
      loadingDescription: "Подтягиваем историю операций, покупки и конфигурацию пакетов.",
      errorTitle: "Не удалось загрузить экономику",
      errorDescription: "Проверьте доступ к backend и повторите запрос.",
      metaPacks: "Пакетов",
      metaLedger: "Операций",
      metaPurchases: "Покупок",
      metaSubscriptions: "Подписок",
      metaRoutes: "Маршрутов",
      activePacksLabel: "Активные паки",
      creditFlowLabel: "Начисления",
      debitFlowLabel: "Списания",
      revenueLabel: "Выручка",
      activeSubscriptionsLabel: "Активные подписки",
      renewalStopsLabel: "Остановки продления",
      activePlansCountLabel: "Активные планы",
      enabledRoutesLabel: "Включенные маршруты",
      packsTitle: "Паки пополнения",
      packsDescription:
        "Редактирование цен, бонуса и видимости пакетов без затрагивания истории покупок.",
      subscriptionPlansTitle: "Premium планы",
      subscriptionPlansDescription:
        "Текущая конфигурация месячных и годовых планов, которую видят мобильный клиент и checkout flow.",
      providerConfigsTitle: "Маршрутизация платежей",
      providerConfigsDescription:
        "Backend-controlled правила выбора App Store, Google Play и Stripe по платформе и региону.",
      providerConfigCreateTitle: "Создать маршрут",
      providerConfigCreateAction: "Добавить маршрут",
      providerConfigTestTitle: "Test Match",
      providerConfigTestAction: "Проверить матч",
      providerConfigMatchLabel: "Сработавший маршрут",
      providerConfigNoMatchLabel: "Совпадений нет для указанных входных условий.",
      subscriptionsTitle: "Активные и недавние подписки",
      subscriptionsDescription:
        "Снимок последних premium подписок по пользователям с провайдером, токенами и датой продления.",
      subscriptionEventsTitle: "Лог событий подписок",
      subscriptionEventsDescription:
        "Последние lifecycle события из store/Stripe flows для диагностики интеграции.",
      tokensShort: "spark",
      packSaved: "Пакет обновлен.",
      packSaveError: "Не удалось сохранить пакет.",
      planSaved: "Premium план обновлен.",
      planSaveError: "Не удалось сохранить Premium план.",
      providerConfigSaved: "Маршрут оплаты обновлен.",
      providerConfigSaveError: "Не удалось сохранить маршрут оплаты.",
      providerConfigCreated: "Маршрут оплаты создан.",
      providerConfigCreateError: "Не удалось создать маршрут оплаты.",
      providerConfigCloned: "Маршрут оплаты клонирован.",
      providerConfigCloneError: "Не удалось клонировать маршрут оплаты.",
      providerConfigDeleted: "Маршрут оплаты удален.",
      providerConfigDeleteError: "Не удалось удалить маршрут оплаты.",
      providerConfigTestError: "Не удалось выполнить тест маршрутизации.",
      planMissingDraft: "План не найден в текущем списке.",
      providerConfigMissingDraft: "Маршрут оплаты не найден в текущем списке.",
      invalidPlanNumbers: "Укажите корректные цену, валюту и лимит токенов для плана.",
      invalidProviderConfig:
        "Заполните регион, минимальную версию приложения, режим маршрута и бонус от 0 до 100%.",
      invalidProviderConfigCreate: "Укажите provider и platform для нового маршрута.",
      invalidProviderConfigMatch:
        "Укажите provider/platform/region/appVersion для теста маршрутизации.",
      packColumn: "Пакет",
      planColumn: "План",
      priceColumn: "Цена",
      grantedColumn: "База",
      bonusColumn: "Бонус",
      sortColumn: "Порядок",
      activeColumn: "Активен",
      actionsColumn: "Действие",
      activeState: "Включен",
      inactiveState: "Скрыт",
      recommendedState: "Рекомендуем",
      savingAction: "Сохраняем...",
      saveAction: "Сохранить",
      noPacks: "Паки пополнения пока не настроены.",
      noSubscriptionPlans: "Premium планы пока не настроены.",
      noProviderConfigs: "Правила маршрутизации платежей пока не настроены.",
      noSubscriptions: "Подписки пока не найдены.",
      noSubscriptionEvents: "События подписок пока не записаны.",
      noDescription: "Без описания",
      ledgerTitle: "Ledger операций",
      ledgerDescription:
        "Последние движения баланса по всем пользователям с источником и причиной.",
      ledgerFilterLabel: "Источник",
      purchaseFilterLabel: "Статус",
      noLedger: "Операций пока нет.",
      purchasesTitle: "Покупки и статусы",
      purchasesDescription: "Последние заказы с итоговым статусом оплаты и начислением spark.",
      noPurchases: "Покупок пока нет.",
      timeColumn: "Время",
      userColumn: "Пользователь",
      deltaColumn: "Delta",
      balanceColumn: "Баланс",
      sourceColumn: "Источник",
      reasonColumn: "Причина",
      amountColumn: "Сумма",
      statusColumn: "Статус",
      billingColumn: "Период",
      tokensColumn: "Лимит токенов",
      providerColumn: "Провайдер",
      platformColumn: "Платформа",
      regionColumn: "Регион",
      productIdsColumn: "Store IDs",
      appleProductLabel: "Apple product ID",
      googleProductLabel: "Google product ID",
      stripePriceLabel: "Stripe price ID",
      flagsColumn: "Флаги",
      modeColumn: "Режим",
      notesLabel: "Заметки",
      renewalColumn: "Следующее списание",
      eventTypeColumn: "Событие",
      processedColumn: "Обработано",
      cancelAtPeriodEndLabel: "Без автопродления",
      externalCheckoutFlag: "External checkout",
      recommendedFlag: "Recommended",
      defaultFlag: "Default",
      externalWarningFlag: "External warning",
      storeDisclosureFlag: "Store disclosure",
      minVersionLabel: "Минимум",
      bonusPercentLabel: "Бонус, %",
      displayLabelLabel: "Название",
      displaySubtitleLabel: "Подзаголовок",
      warningTitleLabel: "Заголовок warning",
      warningMessageLabel: "Текст warning",
      cloneRegionPlaceholder: "Регион для копии",
      cloneAction: "Клонировать",
      deleteAction: "Удалить",
      providerConfigDeleteConfirm: "Удалить этот маршрут оплаты?",
      notProcessedLabel: "Еще не обработано",
    };
  }

  return {
    eyebrow: "Economy and wallet",
    title: "Economy",
    description:
      "System-wide view of balance movement, payment statuses, and top-up packs without opening each user profile.",
    loadingTitle: "Loading economy",
    loadingDescription: "Fetching ledger, purchases, and pack configuration.",
    errorTitle: "Failed to load economy",
    errorDescription: "Check backend availability and try again.",
    metaPacks: "Packs",
    metaLedger: "Ledger rows",
    metaPurchases: "Purchases",
    metaSubscriptions: "Subscriptions",
    metaRoutes: "Routes",
    activePacksLabel: "Active packs",
    creditFlowLabel: "Credits",
    debitFlowLabel: "Debits",
    revenueLabel: "Revenue",
    activeSubscriptionsLabel: "Active subscriptions",
    renewalStopsLabel: "Renewal stops",
    activePlansCountLabel: "Active plans",
    enabledRoutesLabel: "Enabled routes",
    packsTitle: "Top-up packs",
    packsDescription:
      "Update pricing, bonus, and visibility without touching historical purchases.",
    subscriptionPlansTitle: "Premium plans",
    subscriptionPlansDescription:
      "Current monthly and yearly plan configuration used by mobile clients and checkout flows.",
    providerConfigsTitle: "Payment routing",
    providerConfigsDescription:
      "Backend-controlled rules that choose App Store, Google Play, and Stripe by platform and region.",
    providerConfigCreateTitle: "Create route",
    providerConfigCreateAction: "Add route",
    providerConfigTestTitle: "Test match",
    providerConfigTestAction: "Run match",
    providerConfigMatchLabel: "Matched route",
    providerConfigNoMatchLabel: "No route matched the provided input conditions.",
    subscriptionsTitle: "Active and recent subscriptions",
    subscriptionsDescription:
      "Snapshot of recent premium subscriptions with provider, token usage, and renewal date.",
    subscriptionEventsTitle: "Subscription event log",
    subscriptionEventsDescription:
      "Recent lifecycle events from store and Stripe flows for integration diagnostics.",
    tokensShort: "spark",
    packSaved: "Pack updated.",
    packSaveError: "Failed to save pack.",
    planSaved: "Premium plan updated.",
    planSaveError: "Failed to save premium plan.",
    providerConfigSaved: "Payment route updated.",
    providerConfigSaveError: "Failed to save payment route.",
    providerConfigCreated: "Payment route created.",
    providerConfigCreateError: "Failed to create payment route.",
    providerConfigCloned: "Payment route cloned.",
    providerConfigCloneError: "Failed to clone payment route.",
    providerConfigDeleted: "Payment route deleted.",
    providerConfigDeleteError: "Failed to delete payment route.",
    providerConfigTestError: "Failed to run routing test.",
    planMissingDraft: "Premium plan was not found in the current list.",
    providerConfigMissingDraft: "Payment route was not found in the current list.",
    invalidPlanNumbers: "Enter a valid price, currency, and token limit for the plan.",
    invalidProviderConfig:
      "Enter a valid region, minimum app version, routing mode, and 0-100% bonus.",
    invalidProviderConfigCreate: "Enter provider and platform for the new route.",
    invalidProviderConfigMatch: "Enter provider/platform/region/appVersion for routing test.",
    packColumn: "Pack",
    planColumn: "Plan",
    priceColumn: "Price",
    grantedColumn: "Base",
    bonusColumn: "Bonus",
    sortColumn: "Sort",
    activeColumn: "Active",
    actionsColumn: "Action",
    activeState: "On",
    inactiveState: "Hidden",
    recommendedState: "Recommended",
    savingAction: "Saving...",
    saveAction: "Save",
    noPacks: "No top-up packs configured yet.",
    noSubscriptionPlans: "No premium plans configured yet.",
    noProviderConfigs: "No payment routing rules configured yet.",
    noSubscriptions: "No subscriptions found yet.",
    noSubscriptionEvents: "No subscription events recorded yet.",
    noDescription: "No description",
    ledgerTitle: "Wallet ledger",
    ledgerDescription: "Recent balance movements across users with source and reason.",
    ledgerFilterLabel: "Source",
    purchaseFilterLabel: "Status",
    noLedger: "No wallet operations yet.",
    purchasesTitle: "Purchases and statuses",
    purchasesDescription: "Recent orders with payment outcome and spark grant value.",
    noPurchases: "No purchases yet.",
    timeColumn: "Time",
    userColumn: "User",
    deltaColumn: "Delta",
    balanceColumn: "Balance",
    sourceColumn: "Source",
    reasonColumn: "Reason",
    amountColumn: "Amount",
    statusColumn: "Status",
    billingColumn: "Period",
    tokensColumn: "Token limit",
    providerColumn: "Provider",
    platformColumn: "Platform",
    regionColumn: "Region",
    productIdsColumn: "Store IDs",
    appleProductLabel: "Apple product ID",
    googleProductLabel: "Google product ID",
    stripePriceLabel: "Stripe price ID",
    flagsColumn: "Flags",
    modeColumn: "Mode",
    notesLabel: "Notes",
    renewalColumn: "Next renewal",
    eventTypeColumn: "Event",
    processedColumn: "Processed",
    cancelAtPeriodEndLabel: "No auto-renew",
    externalCheckoutFlag: "External checkout",
    recommendedFlag: "Recommended",
    defaultFlag: "Default",
    externalWarningFlag: "External warning",
    storeDisclosureFlag: "Store disclosure",
    minVersionLabel: "Min",
    bonusPercentLabel: "Bonus, %",
    displayLabelLabel: "Label",
    displaySubtitleLabel: "Subtitle",
    warningTitleLabel: "Warning title",
    warningMessageLabel: "Warning message",
    cloneRegionPlaceholder: "Clone region",
    cloneAction: "Clone",
    deleteAction: "Delete",
    providerConfigDeleteConfirm: "Delete this payment route?",
    notProcessedLabel: "Not processed yet",
  };
}

export type EconomyPageText = ReturnType<typeof getEconomyText>;
