import { type Locale } from "@/lib/i18n";

const roleManagementText = {
  ru: {
    eyebrow: "Контроль доступа",
    title: "Управление ролями",
    description:
      "Администраторы и модераторы управляются из этой панели. Premium не считается ролью.",
    adminOnly: "Только администратор",
    adminsTitle: "Администраторы",
    adminsDescription:
      "Список пользователей с полным доступом. Последнего администратора нельзя понизить.",
    moderatorsTitle: "Модераторы",
    moderatorsDescription: "Пользователи с ограниченным доступом к разрешенным разделам.",
    searchTitle: "Назначить модератора",
    searchDescription: "Поиск по email, ID или имени.",
    searchLabel: "Пользователь",
    searchPlaceholder: "email, ID пользователя или имя",
    searchHint: "Введите минимум 2 символа. Поиск обновится автоматически.",
    loading: "Загрузка ролей",
    error: "Не удалось загрузить роли",
    adminsError: "Не удалось загрузить администраторов",
    moderatorsError: "Не удалось загрузить модераторов",
    searchError: "Не удалось выполнить поиск пользователей",
    emptyAdmins: "Администраторы не найдены",
    emptyModerators: "Модераторы не найдены",
    emptySearch: "Введите запрос для поиска пользователя",
    noSearchResults: "Пользователи не найдены",
    assign: "Назначить",
    revoke: "Снять модератора",
    adminAlreadyPrivileged: "Уже администратор",
    moderatorAlreadyPrivileged: "Уже модератор",
    cancel: "Отмена",
    confirmAssignTitle: "Назначить модератора?",
    confirmAssignDescription: "Пользователь получит доступ к разрешенным разделам модерации.",
    confirmRevokeTitle: "Снять модератора?",
    confirmRevokeDescription:
      "Пользователь потеряет доступ модератора. Действие будет записано в журнал аудита.",
    saved: "Роль обновлена",
    failed: "Не удалось обновить роль",
    roleActionsAdminOnly: "Изменять роли может только администратор.",
    assignModeratorLabel: "Назначить модератора пользователю",
    revokeModeratorLabel: "Снять модератора у пользователя",
    created: "Создан",
    retry: "Повторить",
    previous: "Назад",
    next: "Вперёд",
    previousPageLabel: "Предыдущая страница списка ролей",
    nextPageLabel: "Следующая страница списка ролей",
    page: "Страница",
    of: "из",
    showing: "Показано",
    users: "пользователей",
  },
  en: {
    eyebrow: "Access control",
    title: "Role Management",
    description: "Admin and Moderator are managed from this panel. Premium is not a role.",
    adminOnly: "Admin only",
    adminsTitle: "Admins",
    adminsDescription: "Users with full access. The last Admin cannot be downgraded.",
    moderatorsTitle: "Moderators",
    moderatorsDescription: "Users with limited access to permitted sections.",
    searchTitle: "Assign Moderator",
    searchDescription: "Search by email, id, or name.",
    searchLabel: "User",
    searchPlaceholder: "email, user id, or name",
    searchHint: "Enter at least 2 characters. Search updates automatically.",
    loading: "Loading roles",
    error: "Failed to load roles",
    adminsError: "Failed to load admins",
    moderatorsError: "Failed to load moderators",
    searchError: "Failed to search users",
    emptyAdmins: "No admins found",
    emptyModerators: "No moderators found",
    emptySearch: "Enter a query to search users",
    noSearchResults: "No users found",
    assign: "Assign",
    revoke: "Remove Moderator",
    adminAlreadyPrivileged: "Already Admin",
    moderatorAlreadyPrivileged: "Already Moderator",
    cancel: "Cancel",
    confirmAssignTitle: "Assign Moderator?",
    confirmAssignDescription: "The user will get access to permitted moderator sections.",
    confirmRevokeTitle: "Remove Moderator?",
    confirmRevokeDescription:
      "The user will lose moderator access. The action will be written to audit log.",
    saved: "Role updated",
    failed: "Failed to update role",
    roleActionsAdminOnly: "Only Admin can change roles.",
    assignModeratorLabel: "Assign Moderator to",
    revokeModeratorLabel: "Remove Moderator from",
    created: "Created",
    retry: "Retry",
    previous: "Previous",
    next: "Next",
    previousPageLabel: "Previous role list page",
    nextPageLabel: "Next role list page",
    page: "Page",
    of: "of",
    showing: "Showing",
    users: "users",
  },
} as const;

export type RoleManagementPageText = {
  [K in keyof (typeof roleManagementText)["en"]]: string;
};

export function getRoleManagementPageText(locale: Locale): RoleManagementPageText {
  return roleManagementText[locale] as RoleManagementPageText;
}
