import { type Locale } from "@/lib/i18n";

const roleManagementText = {
  ru: {
    adminsTitle: "Администраторы",
    adminRole: "Администратор",
    moderatorsTitle: "Модераторы",
    moderatorRole: "Модератор",
    searchLabel: "Найти пользователя",
    searchPlaceholder: "Email, ID или имя пользователя",
    searchMinimumCharacters: "Введите минимум 2 символа.",
    searchStatusLoading: "Ищем пользователей…",
    searchResultsCount: "Показано",
    clearSearch: "Очистить поиск",
    loading: "Загрузка ролей",
    error: "Не удалось загрузить роли",
    adminsError: "Не удалось загрузить администраторов",
    moderatorsError: "Не удалось загрузить модераторов",
    searchError: "Не удалось выполнить поиск пользователей",
    emptyAdmins: "Администраторы не найдены",
    emptyModerators: "Модераторов пока нет",
    noSearchResults: "Пользователи не найдены",
    assign: "Назначить модератором",
    revoke: "Снять модератора",
    cancel: "Отмена",
    confirmAssignTitle: "Назначить модератора?",
    confirmAssignDescription: "Пользователь получит доступ к разрешенным разделам модерации.",
    confirmRevokeTitle: "Снять модератора?",
    confirmRevokeDescription:
      "Пользователь потеряет доступ модератора. Действие будет записано в журнал аудита.",
    saved: "Роль обновлена",
    failed: "Не удалось обновить роль",
    roleActionsAdminOnly: "Изменять роли может только администратор.",
    assignModeratorLabel: "Назначить модератора пользователю",
    revokeModeratorLabel: "Снять модератора у пользователя",
    openUserProfile: "Открыть профиль пользователя",
    retry: "Повторить",
    previousPageLabel: "Предыдущая страница",
    nextPageLabel: "Следующая страница",
    adminsPaginationLabel: "Страницы администраторов",
    moderatorsPaginationLabel: "Страницы модераторов",
    searchPaginationLabel: "Страницы результатов поиска",
    page: "Страница",
    of: "из",
  },
  en: {
    adminsTitle: "Admins",
    adminRole: "Admin",
    moderatorsTitle: "Moderators",
    moderatorRole: "Moderator",
    searchLabel: "Find a user",
    searchPlaceholder: "Email, user ID, or name",
    searchMinimumCharacters: "Enter at least 2 characters.",
    searchStatusLoading: "Searching users…",
    searchResultsCount: "Showing",
    clearSearch: "Clear search",
    loading: "Loading roles",
    error: "Failed to load roles",
    adminsError: "Failed to load admins",
    moderatorsError: "Failed to load moderators",
    searchError: "Failed to search users",
    emptyAdmins: "No admins found",
    emptyModerators: "No moderators yet",
    noSearchResults: "No users found",
    assign: "Assign Moderator",
    revoke: "Remove Moderator",
    cancel: "Cancel",
    confirmAssignTitle: "Assign Moderator?",
    confirmAssignDescription: "The user will get access to permitted moderator sections.",
    confirmRevokeTitle: "Remove Moderator?",
    confirmRevokeDescription:
      "The user will lose moderator access. The action will be written to audit log.",
    saved: "Role updated",
    failed: "Failed to update role",
    roleActionsAdminOnly: "Only Admin can change roles.",
    assignModeratorLabel: "Assign Moderator to",
    revokeModeratorLabel: "Remove Moderator from",
    openUserProfile: "Open user profile",
    retry: "Retry",
    previousPageLabel: "Previous page",
    nextPageLabel: "Next page",
    adminsPaginationLabel: "Admin pages",
    moderatorsPaginationLabel: "Moderator pages",
    searchPaginationLabel: "Search result pages",
    page: "Page",
    of: "of",
  },
} as const;

export type RoleManagementPageText = {
  [K in keyof (typeof roleManagementText)["en"]]: string;
};

export function getRoleManagementPageText(locale: Locale): RoleManagementPageText {
  return roleManagementText[locale] as RoleManagementPageText;
}
