import { type Locale } from "@/lib/i18n";

const userDetailPetText = {
  ru: {
    title: "Питомцы",
    description: "Профили питомцев, фото, генерации и модерационный статус.",
    noPets: "Питомцы пока не добавлены.",
    loadError: "Не удалось загрузить питомцев.",
    loadingPhotos: "Загружаем фото...",
    photosLoadError: "Не удалось загрузить фото питомца.",
    noPhotos: "Фото нет.",
    loadingGenerations: "Загружаем историю генераций питомца...",
    generationsLoadError: "Не удалось загрузить генерации питомца.",
    noGenerations: "Генераций питомца нет.",
    photosCount: "фото",
    generationsCount: "генераций",
    hide: "Скрыть",
    restore: "Восстановить",
    hidePhoto: "Скрыть фото",
    restorePhoto: "Восстановить фото",
    activeStatus: "Активен",
    hiddenStatus: "Скрыт",
    hidePetLabel: "Скрыть питомца",
    restorePetLabel: "Восстановить питомца",
    hidePhotoLabel: "Скрыть фото питомца",
    restorePhotoLabel: "Восстановить фото питомца",
    needsReview: "Требует проверки",
    hideConfirmTitle: "Скрыть материал?",
    hidePetConfirmDescription:
      "Питомец «{name}» станет скрытым для пользователя до восстановления.",
    hidePhotoConfirmDescription: "Фото питомца «{name}» станет скрытым до восстановления.",
    petStatusUpdated: "Статус питомца обновлён.",
    photoStatusUpdated: "Статус фото обновлён.",
    statusUpdateError: "Не удалось обновить статус питомца.",
    photoStatusUpdateError: "Не удалось обновить статус фото.",
    showDetails: "Показать фото и генерации",
    hideDetails: "Скрыть детали",
    avatar: "Аватар",
    favorite: "Избранное",
    photoAlt: "фото питомца",
    thumbnailReady: "миниатюра готова",
    originalOnly: "только оригинал",
    fallbackTemplate: "Шаблон",
    tokenCostLabel: "Стоимость",
  },
  en: {
    title: "Pets",
    description: "Pet profiles, photos, generation counts, and moderation status.",
    noPets: "No pets yet.",
    loadError: "Failed to load pets.",
    loadingPhotos: "Loading photos...",
    photosLoadError: "Failed to load pet photos.",
    noPhotos: "No photos.",
    loadingGenerations: "Loading pet generation history...",
    generationsLoadError: "Failed to load pet generations.",
    noGenerations: "No pet generations.",
    photosCount: "photos",
    generationsCount: "generations",
    hide: "Hide",
    restore: "Restore",
    hidePhoto: "Hide photo",
    restorePhoto: "Restore photo",
    activeStatus: "Active",
    hiddenStatus: "Hidden",
    hidePetLabel: "Hide pet",
    restorePetLabel: "Restore pet",
    hidePhotoLabel: "Hide pet photo",
    restorePhotoLabel: "Restore pet photo",
    needsReview: "Needs review",
    hideConfirmTitle: "Hide this item?",
    hidePetConfirmDescription: "{name} will be hidden from the user until restored.",
    hidePhotoConfirmDescription: "This photo of {name} will be hidden until restored.",
    petStatusUpdated: "Pet status updated.",
    photoStatusUpdated: "Photo status updated.",
    statusUpdateError: "Failed to update pet status.",
    photoStatusUpdateError: "Failed to update photo status.",
    showDetails: "Show photos and generations",
    hideDetails: "Hide details",
    avatar: "Avatar",
    favorite: "Favorite",
    photoAlt: "pet photo",
    thumbnailReady: "thumbnail ready",
    originalOnly: "original only",
    fallbackTemplate: "Template",
    tokenCostLabel: "Cost",
  },
} as const;

export type UserDetailPetText = { [K in keyof (typeof userDetailPetText)["en"]]: string };

export function getUserDetailPetText(locale: Locale): UserDetailPetText {
  return userDetailPetText[locale] as UserDetailPetText;
}

const userDetailWorkspaceText = {
  ru: {
    pageEyebrow: "Досье пользователя",
    pageDescription: "Вся необходимая информация и действия в одном месте.",
    backToUsers: "К пользователям",
    profileTitle: "Профиль",
    profileDescription: "Статус аккаунта и основные сведения.",
    profileId: "ID профиля",
    profileCreatedAt: "С нами с",
    profileLastActivity: "Последняя активность",
    quickActionsTitle: "Быстрые действия",
    quickWallet: "Изменить баланс",
    quickSupport: "Обращения",
    quickCredit: "+ PawSpark",
    quickPremium: "Premium",
    quickMessage: "Сообщение",
    moreActions: "Дополнительные действия",
    petsMetric: "Питомцы",
    activeSessionsMetric: "Активные сессии",
    tabsLabel: "Раздел досье",
    tabOverview: "Обзор",
    tabWallet: "Экономика",
    tabSupport: "Поддержка",
    tabContent: "Контент",
    tabAccess: "Безопасность",
    overviewTitle: "Активность и использование",
    overviewDescription: "Баланс, покупки и последние действия пользователя.",
    overviewAccountState: "Состояние аккаунта",
    overviewAccountActive: "Аккаунт активен",
    overviewAccountBlocked: "Доступ ограничен",
    overviewSummaryTitle: "Сводка",
    overviewPlan: "Тариф",
    overviewRole: "Роль",
    overviewEmailConfirmed: "Почта подтверждена",
    overviewEmailUnconfirmed: "Почта не подтверждена",
    overviewBalance: "Баланс PawSpark",
    overviewPurchases: "Покупки",
    overviewGenerations: "Генерации",
    overviewActivityTitle: "Последние действия",
    overviewNoActivity: "Здесь появятся важные действия пользователя.",
    activityDocumentsAccepted: "Подтверждены документы",
    activityExternalLogin: "Вход через внешний сервис",
    activityLogin: "Вход в аккаунт",
    activityFailedLogin: "Неудачная попытка входа",
    activityProfileUpdated: "Обновлён профиль",
    activityAccessUpdated: "Изменены права или доступ",
    activityPurchase: "Покупка",
    activityPurchaseCompleted: "Покупка подтверждена",
    activityWallet: "Изменён баланс PawSpark",
    activityGeneration: "Создана генерация",
    activityGenerationFailed: "Генерация не завершилась",
    activityTemplate: "Действие с шаблоном",
    activitySystem: "Системное событие",
    purchaseCompleted: "Оплата подтверждена",
    purchaseIncomplete: "Оплата не завершена",
    generationCompleted: "Готово",
    generationFailed: "Не выполнена",
    generationInProgress: "В процессе",
    supportTitle: "Обращения в поддержку",
    supportDescription: "История диалогов с поддержкой и их текущий статус.",
    supportLoading: "Загружаем обращения пользователя...",
    supportNoTickets: "Пользователь пока не создавал обращений.",
    supportEmptyHint: "Когда они появятся, здесь будут видны статус и последняя активность.",
    supportOpenTicket: "Открыть обращение",
    supportUnread: "Есть непрочитанное",
    supportAssignedTo: "Назначено",
    supportUnassigned: "Не назначено",
    supportPageInfo: "Страница",
    supportPreviousAction: "Назад",
    supportNextAction: "Вперёд",
    supportPreviousPage: "Предыдущая страница обращений",
    supportNextPage: "Следующая страница обращений",
    accessTitle: "Доступ",
    accessDescription:
      "Настройки аккаунта, роли и документы. Изменения применяются сразу и фиксируются в аудите.",
    accessAccountState: "Аккаунт",
    accessAccountHint: "При необходимости ограничьте или верните пользователю доступ к сервису.",
    accessRoles: "Права доступа",
    accessRolesHint: "Роли определяют возможности пользователя в административной панели.",
    accessRoleAssigned: "назначена",
    accessRoleNotAssigned: "не назначена",
    accessAdminCheckPending: "Проверяем, можно ли безопасно отозвать роль администратора.",
    accessAdminCheckError: "Не удалось проверить количество администраторов. Повторите проверку.",
    accessPremium: "Подписка",
    accessPremiumHint: "Проверьте текущий статус подписки перед отменой Premium.",
    accessPremiumProvider: "Провайдер",
    accessPremiumStatus: "Статус",
    accessPremiumLoading: "Проверяем актуальные данные подписки...",
    accessPremiumLoadError:
      "Не удалось проверить провайдера и статус подписки. Отмена заблокирована до повторной проверки.",
    accessPremiumStripeCancellable:
      "Активную Stripe-подписку можно отменить немедленно. Premium будет отозван сразу.",
    accessPremiumRecoveryPending:
      "Предыдущий отзыв Premium не завершён. Повторите действие: оно безопасно продолжит операцию с тем же idempotency key.",
    accessPremiumStoreManaged:
      "Подписка управляется через {provider}. Отмена выполняется в аккаунте магазина пользователя; здесь данные доступны только для чтения.",
    accessPremiumCancellationScheduled:
      "Отмена Stripe уже запланирована на конец оплаченного периода. Повторное действие недоступно.",
    accessPremiumInactive: "Немедленная отмена недоступна для текущего статуса «{status}».",
    accessPremiumUnavailable:
      "Провайдер подписки не поддерживает безопасную отмену из админ-панели. Данные доступны только для чтения.",
    accessPremiumStateChanged:
      "Состояние подписки изменилось во время проверки. Действие не выполнено; проверьте актуальный статус.",
    accessConsent: "Документы и рассылка",
    accessConsentHint: "Справочная информация о принятых документах и настройках писем.",
    accessTerms: "Условия использования",
    accessPrivacy: "Политика конфиденциальности",
    accessMarketing: "Маркетинговые письма",
    consentAccepted: "Принято",
    consentMissing: "Не принято",
    consentEnabled: "Включены",
    consentDisabled: "Отключены",
    requiredAcceptance: "Требуется повторное принятие документов",
    changeRole: "Изменить роль",
    revokePremium: "Отменить Stripe Premium",
    block: "Заблокировать",
    unblock: "Разблокировать",
    deleteTitle: "Удаление аккаунта",
    deleteDescription:
      "Необратимое действие. Используйте его только после проверки юридических оснований и политики хранения данных.",
    deleteUser: "Удалить пользователя",
    actionSuccess: "Данные пользователя обновлены.",
    actionError: "Не удалось обновить данные пользователя.",
    actionRefreshWarning:
      "Изменение применено, но данные не обновились. Обновите страницу перед следующим действием.",
    confirmTitle: "Подтвердить действие?",
    confirmDescription: "Изменение будет применено сразу и записано в журнал аудита.",
    confirmBlockDescription: "Пользователь потеряет доступ к сервису до разблокировки.",
    confirmUnblockDescription: "Пользователь снова сможет пользоваться сервисом.",
    confirmRevokePremiumDescription:
      "Активная Stripe-подписка будет отменена немедленно, а Premium-статус отозван.",
    premiumRevokeReasonLabel: "Причина отзыва",
    premiumRevokeReasonPlaceholder: "Например: подтверждённый запрос пользователя",
    premiumRevokeReasonHint: "Обязательно для журнала аудита.",
    confirmAssignRoleDescription: "Роль будет выдана сразу после подтверждения.",
    confirmRevokeRoleDescription: "Роль будет отозвана сразу после подтверждения.",
    confirmDeleteDescription:
      "Аккаунт и связанные данные будут удалены без возможности восстановления.",
    confirmCancel: "Отмена",
    lastAdminProtected: "Последнего администратора нельзя лишить роли.",
    loadSupportError: "Не удалось загрузить обращения пользователя.",
    showAudit: "Последние действия",
    noAudit: "Событий аудита пока нет.",
    contentPurchases: "Покупки",
    contentGenerations: "Последние генерации",
    noPurchases: "Покупок пока нет.",
    noGenerations: "Генераций пока нет.",
  },
  en: {
    pageEyebrow: "User dossier",
    pageDescription: "Key information and actions in one place.",
    backToUsers: "Back to users",
    profileTitle: "Profile",
    profileDescription: "Account state and key information.",
    profileId: "Profile ID",
    profileCreatedAt: "With us since",
    profileLastActivity: "Last activity",
    quickActionsTitle: "Quick actions",
    quickWallet: "Adjust balance",
    quickSupport: "Support",
    quickCredit: "+ PawSpark",
    quickPremium: "Premium",
    quickMessage: "Message",
    moreActions: "More actions",
    petsMetric: "Pets",
    activeSessionsMetric: "Active sessions",
    tabsLabel: "Dossier section",
    tabOverview: "Overview",
    tabWallet: "Economy",
    tabSupport: "Support",
    tabContent: "Content",
    tabAccess: "Security",
    overviewTitle: "Activity and usage",
    overviewDescription: "Balance, purchases, and this user's latest actions.",
    overviewAccountState: "Account state",
    overviewAccountActive: "Account is active",
    overviewAccountBlocked: "Access is restricted",
    overviewSummaryTitle: "Summary",
    overviewPlan: "Plan",
    overviewRole: "Role",
    overviewEmailConfirmed: "Email confirmed",
    overviewEmailUnconfirmed: "Email not confirmed",
    overviewBalance: "PawSpark balance",
    overviewPurchases: "Purchases",
    overviewGenerations: "Generations",
    overviewActivityTitle: "Recent activity",
    overviewNoActivity: "Important user activity will appear here.",
    activityDocumentsAccepted: "Documents accepted",
    activityExternalLogin: "Signed in with an external service",
    activityLogin: "Signed in",
    activityFailedLogin: "Unsuccessful sign-in attempt",
    activityProfileUpdated: "Profile updated",
    activityAccessUpdated: "Access or permissions updated",
    activityPurchase: "Purchase",
    activityPurchaseCompleted: "Purchase confirmed",
    activityWallet: "PawSpark balance changed",
    activityGeneration: "Generation created",
    activityGenerationFailed: "Generation did not complete",
    activityTemplate: "Template activity",
    activitySystem: "System event",
    purchaseCompleted: "Payment confirmed",
    purchaseIncomplete: "Payment not completed",
    generationCompleted: "Completed",
    generationFailed: "Not completed",
    generationInProgress: "In progress",
    supportTitle: "Support conversations",
    supportDescription: "Support conversation history and its current status.",
    supportLoading: "Loading this user's support conversations...",
    supportNoTickets: "This user has not created any support conversations yet.",
    supportEmptyHint: "When they arrive, their status and latest activity will appear here.",
    supportOpenTicket: "Open conversation",
    supportUnread: "Unread for admin",
    supportAssignedTo: "Assigned to",
    supportUnassigned: "Unassigned",
    supportPageInfo: "Page",
    supportPreviousAction: "Previous",
    supportNextAction: "Next",
    supportPreviousPage: "Previous support conversations page",
    supportNextPage: "Next support conversations page",
    accessTitle: "Access",
    accessDescription:
      "Account settings, roles, and documents. Changes apply immediately and are audited.",
    accessAccountState: "Account",
    accessAccountHint: "Restrict or restore this user's access to the service when necessary.",
    accessRoles: "Access permissions",
    accessRolesHint: "Roles determine this user's capabilities in the admin panel.",
    accessRoleAssigned: "assigned",
    accessRoleNotAssigned: "not assigned",
    accessAdminCheckPending: "Checking whether the administrator role can be removed safely.",
    accessAdminCheckError: "Could not verify the administrator count. Try the check again.",
    accessPremium: "Subscription",
    accessPremiumHint: "Check the current subscription state before cancelling Premium.",
    accessPremiumProvider: "Provider",
    accessPremiumStatus: "Status",
    accessPremiumLoading: "Checking the latest subscription data...",
    accessPremiumLoadError:
      "The subscription provider and status could not be verified. Cancellation is blocked until the check succeeds.",
    accessPremiumStripeCancellable:
      "An active Stripe subscription can be cancelled immediately. Premium access will be revoked at once.",
    accessPremiumRecoveryPending:
      "A previous Premium revocation is incomplete. Retry it safely with the same idempotency key.",
    accessPremiumStoreManaged:
      "This subscription is managed through {provider}. It must be cancelled from the user's store account; this panel is read-only.",
    accessPremiumCancellationScheduled:
      "Stripe cancellation is already scheduled for the end of the paid period. No additional action is available.",
    accessPremiumInactive:
      "Immediate cancellation is unavailable for the current “{status}” status.",
    accessPremiumUnavailable:
      "This subscription provider cannot be cancelled safely from the admin panel. The data is read-only.",
    accessPremiumStateChanged:
      "The subscription changed during verification. No action was taken; review the latest status.",
    accessConsent: "Documents and email",
    accessConsentHint: "Reference information about accepted documents and email preferences.",
    accessTerms: "Terms of use",
    accessPrivacy: "Privacy policy",
    accessMarketing: "Marketing emails",
    consentAccepted: "Accepted",
    consentMissing: "Not accepted",
    consentEnabled: "Enabled",
    consentDisabled: "Disabled",
    requiredAcceptance: "Updated documents require acceptance",
    changeRole: "Change role",
    revokePremium: "Cancel Stripe Premium",
    block: "Block",
    unblock: "Unblock",
    deleteTitle: "Delete account",
    deleteDescription:
      "This action cannot be undone. Use it only after checking legal grounds and retention policy.",
    deleteUser: "Delete user",
    actionSuccess: "User data was updated.",
    actionError: "Could not update user data.",
    actionRefreshWarning:
      "The change was applied, but the latest data could not be loaded. Refresh before another action.",
    confirmTitle: "Confirm action?",
    confirmDescription: "The change applies immediately and is written to the audit log.",
    confirmBlockDescription: "This user will lose access to the service until unblocked.",
    confirmUnblockDescription: "This user will be able to use the service again.",
    confirmRevokePremiumDescription:
      "The active Stripe subscription will be cancelled immediately and Premium access revoked.",
    premiumRevokeReasonLabel: "Revocation reason",
    premiumRevokeReasonPlaceholder: "For example: verified user request",
    premiumRevokeReasonHint: "Required for the audit trail.",
    confirmAssignRoleDescription: "The role will be granted immediately after confirmation.",
    confirmRevokeRoleDescription: "The role will be revoked immediately after confirmation.",
    confirmDeleteDescription: "The account and related data will be permanently deleted.",
    confirmCancel: "Cancel",
    lastAdminProtected: "The last administrator cannot lose the role.",
    loadSupportError: "Could not load this user's support conversations.",
    showAudit: "Recent actions",
    noAudit: "No audit events yet.",
    contentPurchases: "Purchases",
    contentGenerations: "Recent generations",
    noPurchases: "No purchases yet.",
    noGenerations: "No generations yet.",
  },
} as const;

export type UserDetailWorkspaceText = {
  [K in keyof (typeof userDetailWorkspaceText)["en"]]: string;
};

export function getUserDetailWorkspaceText(locale: Locale): UserDetailWorkspaceText {
  return userDetailWorkspaceText[locale] as UserDetailWorkspaceText;
}
