import { type Locale } from "@/lib/i18n";

const userDetailPetText = {
  ru: {
    title: "Питомцы",
    description: "Профили питомцев, фото, генерации и модерационный статус.",
    noPets: "Питомцы пока не добавлены.",
    loadError: "Не удалось загрузить питомцев.",
    loadingPhotos: "Загружаем фото...",
    photosLoadError: "Не удалось загрузить фото питомца.",
    noPhotos: "Фото нет.",
    loadingGenerations: "Загружаем историю генераций питомца...",
    generationsLoadError: "Не удалось загрузить генерации питомца.",
    noGenerations: "Генераций питомца нет.",
    photosCount: "фото",
    generationsCount: "генераций",
    hide: "Скрыть",
    restore: "Восстановить",
    hidePhoto: "Скрыть фото",
    restorePhoto: "Восстановить фото",
    activeStatus: "Активен",
    hiddenStatus: "Скрыт",
    hidePetLabel: "Скрыть питомца",
    restorePetLabel: "Восстановить питомца",
    hidePhotoLabel: "Скрыть фото питомца",
    restorePhotoLabel: "Восстановить фото питомца",
    statusUpdateError: "Не удалось обновить статус питомца.",
    photoStatusUpdateError: "Не удалось обновить статус фото.",
    showDetails: "Показать фото и генерации",
    hideDetails: "Скрыть детали",
    avatar: "Аватар",
    favorite: "Избранное",
    photoAlt: "фото питомца",
    thumbnailReady: "thumbnail готов",
    originalOnly: "только original",
    fallbackTemplate: "Шаблон",
  },
  en: {
    title: "Pets",
    description: "Pet profiles, photos, generation counts, and moderation status.",
    noPets: "No pets yet.",
    loadError: "Failed to load pets.",
    loadingPhotos: "Loading photos...",
    photosLoadError: "Failed to load pet photos.",
    noPhotos: "No photos.",
    loadingGenerations: "Loading pet generation history...",
    generationsLoadError: "Failed to load pet generations.",
    noGenerations: "No pet generations.",
    photosCount: "photos",
    generationsCount: "generations",
    hide: "Hide",
    restore: "Restore",
    hidePhoto: "Hide photo",
    restorePhoto: "Restore photo",
    activeStatus: "Active",
    hiddenStatus: "Hidden",
    hidePetLabel: "Hide pet",
    restorePetLabel: "Restore pet",
    hidePhotoLabel: "Hide pet photo",
    restorePhotoLabel: "Restore pet photo",
    statusUpdateError: "Failed to update pet status.",
    photoStatusUpdateError: "Failed to update photo status.",
    showDetails: "Show photos and generations",
    hideDetails: "Hide details",
    avatar: "Avatar",
    favorite: "Favorite",
    photoAlt: "pet photo",
    thumbnailReady: "thumbnail ready",
    originalOnly: "original only",
    fallbackTemplate: "Template",
  },
} as const;

export type UserDetailPetText = { [K in keyof (typeof userDetailPetText)["en"]]: string };

export function getUserDetailPetText(locale: Locale): UserDetailPetText {
  return userDetailPetText[locale] as UserDetailPetText;
}
