// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using PetMagic.Modules.Templates.Infrastructure.Data;

#nullable disable

namespace PetMagic.Modules.Templates.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TemplatesDbContext))]
    partial class TemplatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAiProviderRequestPermit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BucketUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermitNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_templates_ai_provider_permits_CreatedAtUtc");

                    b.HasIndex("Provider", "BucketUtc", "PermitNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_templates_ai_provider_permits_provider_bucket_slot");

                    b.ToTable("templates_ai_provider_request_permits", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FeedbackMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("GenerationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "CountryCode");

                    b.HasIndex("TemplateId", "CreatedAtUtc");

                    b.HasIndex("TemplateId", "DeviceClass");

                    b.HasIndex("TemplateId", "Source");

                    b.HasIndex("TemplateId", "EventType", "CreatedAtUtc");

                    b.ToTable("templates_analytics_events", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetKind")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "AssetKind")
                        .IsUnique();

                    b.ToTable("templates_assets", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateCatalogChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.HasIndex("TemplateId", "Version");

                    b.ToTable("templates_catalog_changes", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("IsArchived", "Name");

                    b.ToTable("templates_categories", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("GenerationDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("InputPhotoQualityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedReasons")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "UserId");

                    b.HasIndex("TemplateId", "CreatedAtUtc");

                    b.HasIndex("TemplateId", "Rating", "CreatedAtUtc");

                    b.ToTable("templates_generation_feedback", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ChargedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("HiddenByUserAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUserMediaCleanupAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .IsConcurrencyToken()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("MediaImportCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MotionGenerationCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MotionInferenceTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MotionProviderCostUsd")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("MotionProviderRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double?>("OutputVideoDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("PreprocessingCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PreprocessingInferenceTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("PreprocessingProviderRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceMotionUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RefundAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RefundLastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefundLastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResultViewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SourceImageContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceImageFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("SourceImageFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenCost")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedKlingModel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsedPreprocessingModel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserMediaCleanupFailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UserMediaDeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HiddenByUserAtUtc");

                    b.HasIndex("LastUserMediaCleanupAttemptAtUtc");

                    b.HasIndex("UserMediaDeletedAtUtc");

                    b.HasIndex("Status", "CompletedAtUtc");

                    b.HasIndex("Status", "LockedAtUtc")
                        .HasDatabaseName("IX_templates_generation_jobs_Status_LockedAtUtc");

                    b.HasIndex("Status", "QueuedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("Status", "RefundedAtUtc", "RefundLastAttemptedAtUtc");

                    b.HasIndex("TemplateId", "Status", "CreatedAtUtc");

                    b.HasIndex("UserId", "Status", "ResultViewedAtUtc");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_templates_generation_jobs_UserId_Status");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter(""" "Status" IN (1, 2) AND "IdempotencyKey" IS NOT NULL """)
                        .HasDatabaseName("UX_templates_generation_jobs_UserId_IdempotencyKey_active");

                    b.HasIndex("UserId", "RequestHash")
                        .IsUnique()
                        .HasFilter(""" "Status" IN (1, 2) AND "RequestHash" IS NOT NULL """)
                        .HasDatabaseName("UX_templates_generation_jobs_UserId_RequestHash_active");

                    b.ToTable("templates_generation_jobs", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("CharacterOrientation")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ImagePrompt")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<bool?>("KeepOriginalSound")
                        .HasColumnType("boolean");

                    b.Property<string>("KlingModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KlingPrompt")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MusicDescription")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("PetPhotoRequirements")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreprocessingModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreprocessingPrompt")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PromoBadgeMode")
                        .HasColumnType("integer");

                    b.Property<double?>("ReferenceVideoDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("LocalizedTextsJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("TokenCost")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("Version");

                    b.HasIndex("Status", "Category");

                    b.HasIndex("TemplateType", "Status", "UpdatedAtUtc");

                    b.ToTable("templates_items", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateMediaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AttachedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GenerationJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastCleanupAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("GenerationJobId", "LifecycleState");

                    b.HasIndex("LifecycleState", "ExpiresAtUtc");

                    b.HasIndex("TemplateId", "LifecycleState");

                    b.ToTable("templates_media_records", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplatePushDeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "DisabledAtUtc", "LastSeenAtUtc");

                    b.ToTable("templates_push_device_tokens", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAnalyticsEvent", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAsset", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany("Assets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationFeedback", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationJob", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationJob", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateMediaRecord", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationJob", "GenerationJob")
                        .WithMany("MediaRecords")
                        .HasForeignKey("GenerationJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany("MediaRecords")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GenerationJob");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationJob", b =>
                {
                    b.Navigation("MediaRecords");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("MediaRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
