// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetMagic.Modules.Templates.Infrastructure.Data;

#nullable disable

namespace PetMagic.Modules.Templates.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TemplatesDbContext))]
    partial class TemplatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.CreditRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GenerationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId")
                        .IsUnique()
                        .HasDatabaseName("UX_templates_credit_refunds_FeedbackId")
                        .HasFilter(" \"FeedbackId\" IS NOT NULL ");

                    b.HasIndex("GenerationId")
                        .IsUnique()
                        .HasDatabaseName("UX_templates_credit_refunds_GenerationId")
                        .HasFilter(" \"GenerationId\" IS NOT NULL ");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("templates_credit_refunds", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvatarMediaAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvatarMediaAssetId");

                    b.HasIndex("UserId", "IsDeleted", "CreatedAtUtc")
                        .HasDatabaseName("IX_templates_pets_UserId_IsDeleted_CreatedAtUtc");

                    b.ToTable("templates_pets", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.PetAnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("GenerationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PetPhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("PhotosCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceScreen")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPlan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("EventType", "CreatedAtUtc")
                        .HasDatabaseName("IX_tpae_EventType_CreatedAtUtc");

                    b.HasIndex("PetId", "CreatedAtUtc")
                        .HasDatabaseName("IX_tpae_PetId_CreatedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_tpae_UserId_CreatedAtUtc");

                    b.ToTable("templates_pet_analytics_events", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.PetPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvatar")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("active");

                    b.Property<string>("ThumbnailStoragePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId")
                        .IsUnique();

                    b.HasIndex("PetId", "IsDeleted", "SortOrder")
                        .HasDatabaseName("IX_templates_pet_photos_PetId_IsDeleted_SortOrder");

                    b.HasIndex("UserId", "IsDeleted", "CreatedAtUtc")
                        .HasDatabaseName("IX_templates_pet_photos_UserId_IsDeleted_CreatedAtUtc");

                    b.ToTable("templates_pet_photos", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAiProviderRequestPermit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BucketUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermitNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_templates_ai_provider_permits_CreatedAtUtc");

                    b.HasIndex("Provider", "BucketUtc", "PermitNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_templates_ai_provider_permits_provider_bucket_slot");

                    b.ToTable("templates_ai_provider_request_permits", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FeedbackMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("GenerationId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModerationComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModerationStatus", "CreatedAtUtc");

                    b.HasIndex("TemplateId", "CountryCode");

                    b.HasIndex("TemplateId", "CreatedAtUtc");

                    b.HasIndex("TemplateId", "DeviceClass");

                    b.HasIndex("TemplateId", "Source");

                    b.HasIndex("TemplateId", "EventType", "CreatedAtUtc");

                    b.ToTable("templates_analytics_events", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetKind")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "AssetKind")
                        .IsUnique();

                    b.ToTable("templates_assets", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateCatalogChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.HasIndex("TemplateId", "Version");

                    b.ToTable("templates_catalog_changes", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("IsArchived", "Name");

                    b.ToTable("templates_categories", (string)null);
                });

            BuildTemplateGenerationFeedbackEntity(modelBuilder);
            BuildTemplateGenerationJobEntity(modelBuilder);
            BuildTemplateGenerationWatermarkUnlockEntity(modelBuilder);
            BuildTemplateItemEntity(modelBuilder);
            BuildTemplateMediaRecordEntity(modelBuilder);

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateOfTheDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeTextOverride")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("SubtitleOverride")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "StartDate")
                        .HasDatabaseName("IX_templates_otd_template_start_date");

                    b.HasIndex("IsActive", "IsManual", "StartDate", "EndDate")
                        .HasDatabaseName("IX_templates_otd_active_manual_dates");

                    b.ToTable("templates_of_the_day", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateOfTheDaySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTypes")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("AutoModeEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExcludeRecentDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("templates_of_the_day_settings", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplatePushDeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "DisabledAtUtc", "LastSeenAtUtc")
                        .HasDatabaseName("IX_tpdt_UserId_DisabledAtUtc_LastSeenAtUtc");

                    b.ToTable("templates_push_device_tokens", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateWatermarkSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApplyToImages")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApplyToVideos")
                        .HasColumnType("boolean");

                    b.Property<int>("CostCredits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("Opacity")
                        .HasColumnType("double precision");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviewImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PreviewVideoFrameUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("templates_watermark_settings", (string)null);
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.CreditRefund", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationFeedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateGenerationJob", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Feedback");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.PetPhoto", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateMediaRecord", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.Pet", "Pet")
                        .WithMany("Photos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAnalyticsEvent", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateAsset", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany("Assets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            BuildTemplateGenerationFeedbackRelationships(modelBuilder);
            BuildTemplateGenerationJobRelationships(modelBuilder);
            BuildTemplateGenerationWatermarkUnlockRelationships(modelBuilder);
            BuildTemplateMediaRecordRelationships(modelBuilder);

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateOfTheDay", b =>
                {
                    b.HasOne("PetMagic.Modules.Templates.Infrastructure.Entities.TemplateItem", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetMagic.Modules.Templates.Infrastructure.Entities.Pet", b =>
                {
                    b.Navigation("Photos");
                });

            BuildTemplateGenerationJobNavigations(modelBuilder);
            BuildTemplateItemNavigations(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
